<?php

// Data functions for table tblAccessions

// This script and data application were generated by AppGini 5.30
// Download AppGini for free from http://bigprof.com/appgini/download/

function tblAccessions_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('tblAccessions');
	if(!$arrPerm[1]){
		return false;
	}

	$data['EntityID'] = makeSafe($_POST['EntityID']);
		if($data['EntityID'] == empty_lookup_value){ $data['EntityID'] = ''; }
	$data['MediumTypeID'] = makeSafe($_POST['MediumTypeID']);
		if($data['MediumTypeID'] == empty_lookup_value){ $data['MediumTypeID'] = ''; }
	$data['ContentTypeID'] = makeSafe($_POST['ContentTypeID']);
		if($data['ContentTypeID'] == empty_lookup_value){ $data['ContentTypeID'] = ''; }
	$data['CaptionText'] = makeSafe($_POST['CaptionText']);
		if($data['CaptionText'] == empty_lookup_value){ $data['CaptionText'] = ''; }
	$data['URL'] = makeSafe($_POST['URL']);
		if($data['URL'] == empty_lookup_value){ $data['URL'] = ''; }
	$data['SourceID'] = makeSafe($_POST['SourceID']);
		if($data['SourceID'] == empty_lookup_value){ $data['SourceID'] = ''; }
	$data['Credits'] = makeSafe($_POST['Credits']);
		if($data['Credits'] == empty_lookup_value){ $data['Credits'] = ''; }
	$data['ContributorID'] = makeSafe($_POST['ContributorID']);
		if($data['ContributorID'] == empty_lookup_value){ $data['ContributorID'] = ''; }
	$data['StyleID'] = makeSafe($_POST['StyleID']);
		if($data['StyleID'] == empty_lookup_value){ $data['StyleID'] = ''; }
	$data['CountryID'] = makeSafe($_POST['CountryID']);
		if($data['CountryID'] == empty_lookup_value){ $data['CountryID'] = ''; }
	$data['CreationDate'] = makeSafe($_POST['CreationDate']);
		if($data['CreationDate'] == empty_lookup_value){ $data['CreationDate'] = ''; }
	$data['AccessionEntryDate'] = makeSafe($_POST['AccessionEntryDate']);
		if($data['AccessionEntryDate'] == empty_lookup_value){ $data['AccessionEntryDate'] = ''; }
	$data['ApprovalID'] = makeSafe($_POST['ApprovalID']);
		if($data['ApprovalID'] == empty_lookup_value){ $data['ApprovalID'] = ''; }
	$data['Comments'] = makeSafe($_POST['Comments']);
		if($data['Comments'] == empty_lookup_value){ $data['Comments'] = ''; }
	$data['Online'] = makeSafe($_POST['Online']);
		if($data['Online'] == empty_lookup_value){ $data['Online'] = ''; }

	// hook: tblAccessions_before_insert
	if(function_exists('tblAccessions_before_insert')){
		$args=array();
		if(!tblAccessions_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `tblAccessions` set       `EntityID`=' . (($data['EntityID'] !== '' && $data['EntityID'] !== NULL) ? "'{$data['EntityID']}'" : 'NULL') . ', `MediumTypeID`=' . (($data['MediumTypeID'] !== '' && $data['MediumTypeID'] !== NULL) ? "'{$data['MediumTypeID']}'" : 'NULL') . ', `ContentTypeID`=' . (($data['ContentTypeID'] !== '' && $data['ContentTypeID'] !== NULL) ? "'{$data['ContentTypeID']}'" : 'NULL') . ', `CaptionText`=' . (($data['CaptionText'] !== '' && $data['CaptionText'] !== NULL) ? "'{$data['CaptionText']}'" : 'NULL') . ', `URL`=' . (($data['URL'] !== '' && $data['URL'] !== NULL) ? "'{$data['URL']}'" : 'NULL') . ', `SourceID`=' . (($data['SourceID'] !== '' && $data['SourceID'] !== NULL) ? "'{$data['SourceID']}'" : 'NULL') . ', `Credits`=' . (($data['Credits'] !== '' && $data['Credits'] !== NULL) ? "'{$data['Credits']}'" : 'NULL') . ', `ContributorID`=' . (($data['ContributorID'] !== '' && $data['ContributorID'] !== NULL) ? "'{$data['ContributorID']}'" : 'NULL') . ', `StyleID`=' . (($data['StyleID'] !== '' && $data['StyleID'] !== NULL) ? "'{$data['StyleID']}'" : 'NULL') . ', `CountryID`=' . (($data['CountryID'] !== '' && $data['CountryID'] !== NULL) ? "'{$data['CountryID']}'" : 'NULL') . ', `CreationDate`=' . (($data['CreationDate'] !== '' && $data['CreationDate'] !== NULL) ? "'{$data['CreationDate']}'" : 'NULL') . ', `AccessionEntryDate`=' . (($data['AccessionEntryDate'] !== '' && $data['AccessionEntryDate'] !== NULL) ? "'{$data['AccessionEntryDate']}'" : 'NULL') . ', `ApprovalID`=' . (($data['ApprovalID'] !== '' && $data['ApprovalID'] !== NULL) ? "'{$data['ApprovalID']}'" : 'NULL') . ', `Comments`=' . (($data['Comments'] !== '' && $data['Comments'] !== NULL) ? "'{$data['Comments']}'" : 'NULL') . ', `Online`=' . (($data['Online'] !== '' && $data['Online'] !== NULL) ? "'{$data['Online']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"tblAccessions_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=db_insert_id(db_link());

	// hook: tblAccessions_after_insert
	if(function_exists('tblAccessions_after_insert')){
		$res = sql("select * from `tblAccessions` where `ID`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!tblAccessions_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='tblAccessions', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function tblAccessions_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('tblAccessions');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tblAccessions' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tblAccessions' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: tblAccessions_before_delete
	if(function_exists('tblAccessions_before_delete')){
		$args=array();
		if(!tblAccessions_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: tblSidebarEntries
	$res = sql("select `ID` from `tblAccessions` where `ID`='$selected_id'", $eo);
	$ID = db_fetch_row($res);
	$rires = sql("select count(1) from `tblSidebarEntries` where `AccessionID`='".addslashes($ID[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tblSidebarEntries", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tblSidebarEntries", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input tabindex=\"2\" type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tblAccessions_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input tabindex=\"2\" type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tblAccessions_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `tblAccessions` where `ID`='$selected_id'", $eo);

	// hook: tblAccessions_after_delete
	if(function_exists('tblAccessions_after_delete')){
		$args=array();
		tblAccessions_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='tblAccessions' and pkValue='$selected_id'", $eo);
}

function tblAccessions_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('tblAccessions');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tblAccessions' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tblAccessions' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['EntityID'] = makeSafe($_POST['EntityID']);
		if($data['EntityID'] == empty_lookup_value){ $data['EntityID'] = ''; }
	$data['MediumTypeID'] = makeSafe($_POST['MediumTypeID']);
		if($data['MediumTypeID'] == empty_lookup_value){ $data['MediumTypeID'] = ''; }
	$data['ContentTypeID'] = makeSafe($_POST['ContentTypeID']);
		if($data['ContentTypeID'] == empty_lookup_value){ $data['ContentTypeID'] = ''; }
	$data['CaptionText'] = makeSafe($_POST['CaptionText']);
		if($data['CaptionText'] == empty_lookup_value){ $data['CaptionText'] = ''; }
	$data['URL'] = makeSafe($_POST['URL']);
		if($data['URL'] == empty_lookup_value){ $data['URL'] = ''; }
	$data['SourceID'] = makeSafe($_POST['SourceID']);
		if($data['SourceID'] == empty_lookup_value){ $data['SourceID'] = ''; }
	$data['Credits'] = makeSafe($_POST['Credits']);
		if($data['Credits'] == empty_lookup_value){ $data['Credits'] = ''; }
	$data['ContributorID'] = makeSafe($_POST['ContributorID']);
		if($data['ContributorID'] == empty_lookup_value){ $data['ContributorID'] = ''; }
	$data['StyleID'] = makeSafe($_POST['StyleID']);
		if($data['StyleID'] == empty_lookup_value){ $data['StyleID'] = ''; }
	$data['CountryID'] = makeSafe($_POST['CountryID']);
		if($data['CountryID'] == empty_lookup_value){ $data['CountryID'] = ''; }
	$data['CreationDate'] = makeSafe($_POST['CreationDate']);
		if($data['CreationDate'] == empty_lookup_value){ $data['CreationDate'] = ''; }
	$data['AccessionEntryDate'] = makeSafe($_POST['AccessionEntryDate']);
		if($data['AccessionEntryDate'] == empty_lookup_value){ $data['AccessionEntryDate'] = ''; }
	$data['ApprovalID'] = makeSafe($_POST['ApprovalID']);
		if($data['ApprovalID'] == empty_lookup_value){ $data['ApprovalID'] = ''; }
	$data['Comments'] = makeSafe($_POST['Comments']);
		if($data['Comments'] == empty_lookup_value){ $data['Comments'] = ''; }
	$data['Online'] = makeSafe($_POST['Online']);
		if($data['Online'] == empty_lookup_value){ $data['Online'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: tblAccessions_before_update
	if(function_exists('tblAccessions_before_update')){
		$args=array();
		if(!tblAccessions_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `tblAccessions` set       `EntityID`=' . (($data['EntityID'] !== '' && $data['EntityID'] !== NULL) ? "'{$data['EntityID']}'" : 'NULL') . ', `MediumTypeID`=' . (($data['MediumTypeID'] !== '' && $data['MediumTypeID'] !== NULL) ? "'{$data['MediumTypeID']}'" : 'NULL') . ', `ContentTypeID`=' . (($data['ContentTypeID'] !== '' && $data['ContentTypeID'] !== NULL) ? "'{$data['ContentTypeID']}'" : 'NULL') . ', `CaptionText`=' . (($data['CaptionText'] !== '' && $data['CaptionText'] !== NULL) ? "'{$data['CaptionText']}'" : 'NULL') . ', `URL`=' . (($data['URL'] !== '' && $data['URL'] !== NULL) ? "'{$data['URL']}'" : 'NULL') . ', `SourceID`=' . (($data['SourceID'] !== '' && $data['SourceID'] !== NULL) ? "'{$data['SourceID']}'" : 'NULL') . ', `Credits`=' . (($data['Credits'] !== '' && $data['Credits'] !== NULL) ? "'{$data['Credits']}'" : 'NULL') . ', `ContributorID`=' . (($data['ContributorID'] !== '' && $data['ContributorID'] !== NULL) ? "'{$data['ContributorID']}'" : 'NULL') . ', `StyleID`=' . (($data['StyleID'] !== '' && $data['StyleID'] !== NULL) ? "'{$data['StyleID']}'" : 'NULL') . ', `CountryID`=' . (($data['CountryID'] !== '' && $data['CountryID'] !== NULL) ? "'{$data['CountryID']}'" : 'NULL') . ', `CreationDate`=' . (($data['CreationDate'] !== '' && $data['CreationDate'] !== NULL) ? "'{$data['CreationDate']}'" : 'NULL') . ', `AccessionEntryDate`=' . (($data['AccessionEntryDate'] !== '' && $data['AccessionEntryDate'] !== NULL) ? "'{$data['AccessionEntryDate']}'" : 'NULL') . ', `ApprovalID`=' . (($data['ApprovalID'] !== '' && $data['ApprovalID'] !== NULL) ? "'{$data['ApprovalID']}'" : 'NULL') . ', `Comments`=' . (($data['Comments'] !== '' && $data['Comments'] !== NULL) ? "'{$data['Comments']}'" : 'NULL') . ', `Online`=' . (($data['Online'] !== '' && $data['Online'] !== NULL) ? "'{$data['Online']}'" : 'NULL') . " where `ID`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="tblAccessions_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: tblAccessions_after_update
	if(function_exists('tblAccessions_after_update')){
		$res = sql("SELECT * FROM `tblAccessions` WHERE `ID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['ID'];
		$args = array();
		if(!tblAccessions_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='tblAccessions' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function tblAccessions_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('tblAccessions');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_EntityID = thisOr(undo_magic_quotes($_REQUEST['filterer_EntityID']), '');
	$filterer_MediumTypeID = thisOr(undo_magic_quotes($_REQUEST['filterer_MediumTypeID']), '');
	$filterer_ContentTypeID = thisOr(undo_magic_quotes($_REQUEST['filterer_ContentTypeID']), '');
	$filterer_ContributorID = thisOr(undo_magic_quotes($_REQUEST['filterer_ContributorID']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: EntityID
	$combo_EntityID = new DataCombo;
	// combobox: MediumTypeID
	$combo_MediumTypeID = new DataCombo;
	// combobox: ContentTypeID
	$combo_ContentTypeID = new DataCombo;
	// combobox: ContributorID
	$combo_ContributorID = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tblAccessions' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tblAccessions' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `tblAccessions` where `ID`='".makeSafe($selected_id)."'", $eo);
		$row = db_fetch_array($res);
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_EntityID->SelectedData = $row['EntityID'];
		$combo_MediumTypeID->SelectedData = $row['MediumTypeID'];
		$combo_ContentTypeID->SelectedData = $row['ContentTypeID'];
		$combo_ContributorID->SelectedData = $row['ContributorID'];
	}else{
		$combo_EntityID->SelectedData = $filterer_EntityID;
		$combo_MediumTypeID->SelectedData = $filterer_MediumTypeID;
		$combo_ContentTypeID->SelectedData = $filterer_ContentTypeID;
		$combo_ContributorID->SelectedData = $filterer_ContributorID;
	}
	$combo_EntityID->HTML = '<span id="EntityID-container' . $rnd1 . '"></span><input type="hidden" name="EntityID" id="EntityID' . $rnd1 . '">';
	$combo_EntityID->MatchText = '<span id="EntityID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="EntityID" id="EntityID' . $rnd1 . '">';
	$combo_MediumTypeID->HTML = '<span id="MediumTypeID-container' . $rnd1 . '"></span><input type="hidden" name="MediumTypeID" id="MediumTypeID' . $rnd1 . '">';
	$combo_MediumTypeID->MatchText = '<span id="MediumTypeID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="MediumTypeID" id="MediumTypeID' . $rnd1 . '">';
	$combo_ContentTypeID->HTML = '<span id="ContentTypeID-container' . $rnd1 . '"></span><input type="hidden" name="ContentTypeID" id="ContentTypeID' . $rnd1 . '">';
	$combo_ContentTypeID->MatchText = '<span id="ContentTypeID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="ContentTypeID" id="ContentTypeID' . $rnd1 . '">';
	$combo_ContributorID->HTML = '<span id="ContributorID-container' . $rnd1 . '"></span><input type="hidden" name="ContributorID" id="ContributorID' . $rnd1 . '">';
	$combo_ContributorID->MatchText = '<span id="ContributorID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="ContributorID" id="ContributorID' . $rnd1 . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_EntityID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['EntityID'] : $filterer_EntityID); ?>"};
		var current_MediumTypeID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['MediumTypeID'] : $filterer_MediumTypeID); ?>"};
		var current_ContentTypeID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['ContentTypeID'] : $filterer_ContentTypeID); ?>"};
		var current_ContributorID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['ContributorID'] : $filterer_ContributorID); ?>"};
		
		jQuery(function() {
			EntityID_reload__RAND__();
			MediumTypeID_reload__RAND__();
			ContentTypeID_reload__RAND__();
			ContributorID_reload__RAND__();
		});
		function EntityID_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#EntityID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_EntityID__RAND__.value, t: 'tblAccessions', f: 'EntityID' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="EntityID"]').val(resp.results[0].id);
						jQuery('[id=EntityID-container-readonly__RAND__]').html('<span id="EntityID-match-text">' + resp.results[0].text + '</span>');


						if(typeof(EntityID_update_autofills__RAND__) == 'function') EntityID_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'tblAccessions', f: 'EntityID' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_EntityID__RAND__.value = e.added.id;
				current_EntityID__RAND__.text = e.added.text;
				jQuery('[name="EntityID"]').val(e.added.id);


				if(typeof(EntityID_update_autofills__RAND__) == 'function') EntityID_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_EntityID__RAND__.value, t: 'tblAccessions', f: 'EntityID' }
			}).done(function(resp){
				jQuery('[id=EntityID-container__RAND__], [id=EntityID-container-readonly__RAND__]').html('<span id="EntityID-match-text">' + resp.results[0].text + '</span>');

				if(typeof(EntityID_update_autofills__RAND__) == 'function') EntityID_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function MediumTypeID_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#MediumTypeID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_MediumTypeID__RAND__.value, t: 'tblAccessions', f: 'MediumTypeID' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="MediumTypeID"]').val(resp.results[0].id);
						jQuery('[id=MediumTypeID-container-readonly__RAND__]').html('<span id="MediumTypeID-match-text">' + resp.results[0].text + '</span>');


						if(typeof(MediumTypeID_update_autofills__RAND__) == 'function') MediumTypeID_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'tblAccessions', f: 'MediumTypeID' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_MediumTypeID__RAND__.value = e.added.id;
				current_MediumTypeID__RAND__.text = e.added.text;
				jQuery('[name="MediumTypeID"]').val(e.added.id);


				if(typeof(MediumTypeID_update_autofills__RAND__) == 'function') MediumTypeID_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_MediumTypeID__RAND__.value, t: 'tblAccessions', f: 'MediumTypeID' }
			}).done(function(resp){
				jQuery('[id=MediumTypeID-container__RAND__], [id=MediumTypeID-container-readonly__RAND__]').html('<span id="MediumTypeID-match-text">' + resp.results[0].text + '</span>');

				if(typeof(MediumTypeID_update_autofills__RAND__) == 'function') MediumTypeID_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function ContentTypeID_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#ContentTypeID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_ContentTypeID__RAND__.value, t: 'tblAccessions', f: 'ContentTypeID' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="ContentTypeID"]').val(resp.results[0].id);
						jQuery('[id=ContentTypeID-container-readonly__RAND__]').html('<span id="ContentTypeID-match-text">' + resp.results[0].text + '</span>');


						if(typeof(ContentTypeID_update_autofills__RAND__) == 'function') ContentTypeID_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'tblAccessions', f: 'ContentTypeID' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_ContentTypeID__RAND__.value = e.added.id;
				current_ContentTypeID__RAND__.text = e.added.text;
				jQuery('[name="ContentTypeID"]').val(e.added.id);


				if(typeof(ContentTypeID_update_autofills__RAND__) == 'function') ContentTypeID_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_ContentTypeID__RAND__.value, t: 'tblAccessions', f: 'ContentTypeID' }
			}).done(function(resp){
				jQuery('[id=ContentTypeID-container__RAND__], [id=ContentTypeID-container-readonly__RAND__]').html('<span id="ContentTypeID-match-text">' + resp.results[0].text + '</span>');

				if(typeof(ContentTypeID_update_autofills__RAND__) == 'function') ContentTypeID_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function ContributorID_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#ContributorID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_ContributorID__RAND__.value, t: 'tblAccessions', f: 'ContributorID' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="ContributorID"]').val(resp.results[0].id);
						jQuery('[id=ContributorID-container-readonly__RAND__]').html('<span id="ContributorID-match-text">' + resp.results[0].text + '</span>');


						if(typeof(ContributorID_update_autofills__RAND__) == 'function') ContributorID_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'tblAccessions', f: 'ContributorID' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_ContributorID__RAND__.value = e.added.id;
				current_ContributorID__RAND__.text = e.added.text;
				jQuery('[name="ContributorID"]').val(e.added.id);


				if(typeof(ContributorID_update_autofills__RAND__) == 'function') ContributorID_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_ContributorID__RAND__.value, t: 'tblAccessions', f: 'ContributorID' }
			}).done(function(resp){
				jQuery('[id=ContributorID-container__RAND__], [id=ContributorID-container-readonly__RAND__]').html('<span id="ContributorID-match-text">' + resp.results[0].text + '</span>');

				if(typeof(ContributorID_update_autofills__RAND__) == 'function') ContributorID_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php
	
	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/tblAccessions_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/tblAccessions_templateDV.html');
	}

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'tblAccession details', $templateCode);
	$templateCode=str_replace('<%%RND1%%>', $rnd1, $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return tblAccessions_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return tblAccessions_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return tblAccessions_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#EntityID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#EntityID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#MediumTypeID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#MediumTypeID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#ContentTypeID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#ContentTypeID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#CaptionText').replaceWith('<p class=\"form-control-static\" id=\"CaptionText\">' + (jQuery('#CaptionText').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#URL').replaceWith('<p class=\"form-control-static\" id=\"URL\">' + (jQuery('#URL').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#SourceID').replaceWith('<p class=\"form-control-static\" id=\"SourceID\">' + (jQuery('#SourceID').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#Credits').replaceWith('<p class=\"form-control-static\" id=\"Credits\">' + (jQuery('#Credits').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#ContributorID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#ContributorID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#StyleID').replaceWith('<p class=\"form-control-static\" id=\"StyleID\">' + (jQuery('#StyleID').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#CountryID').replaceWith('<p class=\"form-control-static\" id=\"CountryID\">' + (jQuery('#CountryID').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#CreationDate').replaceWith('<p class=\"form-control-static\" id=\"CreationDate\">' + (jQuery('#CreationDate').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#AccessionEntryDate').replaceWith('<p class=\"form-control-static\" id=\"AccessionEntryDate\">' + (jQuery('#AccessionEntryDate').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#ApprovalID').replaceWith('<p class=\"form-control-static\" id=\"ApprovalID\">' + (jQuery('#ApprovalID').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#Comments').replaceWith('<p class=\"form-control-static\" id=\"Comments\">' + (jQuery('#Comments').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#Online').prop('disabled', true);\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(EntityID)%%>', $combo_EntityID->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(EntityID)%%>', $combo_EntityID->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(EntityID)%%>', urlencode($combo_EntityID->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(MediumTypeID)%%>', $combo_MediumTypeID->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(MediumTypeID)%%>', $combo_MediumTypeID->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(MediumTypeID)%%>', urlencode($combo_MediumTypeID->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(ContentTypeID)%%>', $combo_ContentTypeID->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(ContentTypeID)%%>', $combo_ContentTypeID->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(ContentTypeID)%%>', urlencode($combo_ContentTypeID->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(ContributorID)%%>', $combo_ContributorID->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(ContributorID)%%>', $combo_ContributorID->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(ContributorID)%%>', urlencode($combo_ContributorID->MatchText), $templateCode);

	// process foreign key links
	if($selected_id){
		$templateCode=str_replace('<%%PLINK(EntityID)%%>', ($combo_EntityID->SelectedData ? "<span id=\"tblEntities_plink1\" class=\"hidden\"><a class=\"btn btn-default\" href=\"tblEntities_view.php?SelectedID=" . urlencode($combo_EntityID->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
		$templateCode=str_replace('<%%PLINK(MediumTypeID)%%>', ($combo_MediumTypeID->SelectedData ? "<span id=\"tblSubGalleryTypes_plink2\" class=\"hidden\"><a class=\"btn btn-default\" href=\"tblSubGalleryTypes_view.php?SelectedID=" . urlencode($combo_MediumTypeID->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
		$templateCode=str_replace('<%%PLINK(ContentTypeID)%%>', ($combo_ContentTypeID->SelectedData ? "<span id=\"tblContentTypes_plink3\" class=\"hidden\"><a class=\"btn btn-default\" href=\"tblContentTypes_view.php?SelectedID=" . urlencode($combo_ContentTypeID->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
		$templateCode=str_replace('<%%PLINK(ContributorID)%%>', ($combo_ContributorID->SelectedData ? "<span id=\"tblContributors_plink4\" class=\"hidden\"><a class=\"btn btn-default\" href=\"tblContributors_view.php?SelectedID=" . urlencode($combo_ContributorID->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(ID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(EntityID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(MediumTypeID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ContentTypeID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(CaptionText)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(URL)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(SourceID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Credits)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ContributorID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(StyleID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(CountryID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(CreationDate)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(AccessionEntryDate)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ApprovalID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Comments)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Online)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(ID)%%>', htmlspecialchars($row['ID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ID)%%>', urlencode($urow['ID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(EntityID)%%>', htmlspecialchars($row['EntityID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(EntityID)%%>', urlencode($urow['EntityID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(MediumTypeID)%%>', htmlspecialchars($row['MediumTypeID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MediumTypeID)%%>', urlencode($urow['MediumTypeID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ContentTypeID)%%>', htmlspecialchars($row['ContentTypeID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ContentTypeID)%%>', urlencode($urow['ContentTypeID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(CaptionText)%%>', htmlspecialchars($row['CaptionText'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CaptionText)%%>', urlencode($urow['CaptionText']), $templateCode);
		$templateCode=str_replace('<%%VALUE(URL)%%>', htmlspecialchars($row['URL'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(URL)%%>', urlencode($urow['URL']), $templateCode);
		$templateCode=str_replace('<%%VALUE(SourceID)%%>', htmlspecialchars($row['SourceID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(SourceID)%%>', urlencode($urow['SourceID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Credits)%%>', htmlspecialchars($row['Credits'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Credits)%%>', urlencode($urow['Credits']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ContributorID)%%>', htmlspecialchars($row['ContributorID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ContributorID)%%>', urlencode($urow['ContributorID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(StyleID)%%>', htmlspecialchars($row['StyleID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(StyleID)%%>', urlencode($urow['StyleID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(CountryID)%%>', htmlspecialchars($row['CountryID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CountryID)%%>', urlencode($urow['CountryID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(CreationDate)%%>', htmlspecialchars($row['CreationDate'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CreationDate)%%>', urlencode($urow['CreationDate']), $templateCode);
		$templateCode=str_replace('<%%VALUE(AccessionEntryDate)%%>', htmlspecialchars($row['AccessionEntryDate'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(AccessionEntryDate)%%>', urlencode($urow['AccessionEntryDate']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ApprovalID)%%>', htmlspecialchars($row['ApprovalID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ApprovalID)%%>', urlencode($urow['ApprovalID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Comments)%%>', htmlspecialchars($row['Comments'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Comments)%%>', urlencode($urow['Comments']), $templateCode);
		$templateCode=str_replace('<%%CHECKED(Online)%%>', ($row['Online'] ? "checked" : ""), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(ID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(EntityID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(EntityID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(MediumTypeID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MediumTypeID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ContentTypeID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ContentTypeID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(CaptionText)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CaptionText)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(URL)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(URL)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(SourceID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(SourceID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Credits)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Credits)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ContributorID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ContributorID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(StyleID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(StyleID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(CountryID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CountryID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(CreationDate)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CreationDate)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(AccessionEntryDate)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(AccessionEntryDate)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ApprovalID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ApprovalID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Comments)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Comments)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%CHECKED(Online)%%>', '', $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x']==''){
		$templateCode.="\n\n<script>jQuery(function(){\n";
		$arrTables=getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\tjQuery('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('#xs_{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('[id^=\"{$name}_plink\"]').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode.="<script>";
	$templateCode.="document.observe('dom:loaded', function() {";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: tblAccessions_dv
	if(function_exists('tblAccessions_dv')){
		$args=array();
		tblAccessions_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>