<?php
// This script and data application were generated by AppGini 5.30
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/tblContentTypes.php");
	include("$currDir/tblContentTypes_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('tblContentTypes');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "tblContentTypes";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`tblContentTypes`.`ID`" => "ID",
		"`tblContentTypes`.`Name`" => "Name"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`tblContentTypes`.`ID`',
		2 => 2
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`tblContentTypes`.`ID`" => "ID",
		"`tblContentTypes`.`Name`" => "Name"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`tblContentTypes`.`ID`" => "ID",
		"`tblContentTypes`.`Name`" => "Name"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`tblContentTypes`.`ID`" => "ID",
		"`tblContentTypes`.`Name`" => "Name"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`tblContentTypes` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "tblContentTypes_view.php";
	$x->RedirectAfterInsert = "tblContentTypes_view.php?SelectedID=#ID#";
	$x->TableTitle = "tblContentTypes";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`tblContentTypes`.`ID`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150);
	$x->ColCaption = array("ID", "Name");
	$x->ColFieldName = array('ID', 'Name');
	$x->ColNumber  = array(1, 2);

	$x->Template = 'templates/tblContentTypes_templateTV.html';
	$x->SelectedTemplate = 'templates/tblContentTypes_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblContentTypes`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblContentTypes' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblContentTypes`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblContentTypes' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`tblContentTypes`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tblContentTypes_init
	$render=TRUE;
	if(function_exists('tblContentTypes_init')){
		$args=array();
		$render=tblContentTypes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tblContentTypes_header
	$headerCode='';
	if(function_exists('tblContentTypes_header')){
		$args=array();
		$headerCode=tblContentTypes_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: tblContentTypes_footer
	$footerCode='';
	if(function_exists('tblContentTypes_footer')){
		$args=array();
		$footerCode=tblContentTypes_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>