<?php
// This script and data application were generated by AppGini 5.30
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/tblContributors.php");
	include("$currDir/tblContributors_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('tblContributors');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "tblContributors";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`tblContributors`.`ID`" => "ID",
		"`tblContributors`.`FName`" => "FName",
		"`tblContributors`.`LName`" => "LName",
		"`tblContributors`.`Email`" => "Email",
		"`tblContributors`.`PW`" => "PW",
		"`tblContributors`.`Organization`" => "Organization",
		"`tblContributors`.`ScopeID`" => "ScopeID",
		"IF(    CHAR_LENGTH(`tblContributors1`.`ID`) || CHAR_LENGTH(`tblContributors1`.`LName`), CONCAT_WS('',   `tblContributors1`.`ID`, ': ', `tblContributors1`.`LName`), '') /* ParentID */" => "ParentID",
		"`tblContributors`.`AdminLevel`" => "AdminLevel",
		"if(`tblContributors`.`CreationDate`,date_format(`tblContributors`.`CreationDate`,'%m/%d/%Y'),'')" => "CreationDate",
		"if(`tblContributors`.`ExpirationDate`,date_format(`tblContributors`.`ExpirationDate`,'%m/%d/%Y'),'')" => "ExpirationDate",
		"if(`tblContributors`.`LastAccessDate`,date_format(`tblContributors`.`LastAccessDate`,'%m/%d/%Y'),'')" => "LastAccessDate",
		"concat('<img src=\"', if(`tblContributors`.`Online`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "Online"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`tblContributors`.`ID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`tblContributors`.`ScopeID`',
		8 => 8,
		9 => '`tblContributors`.`AdminLevel`',
		10 => '`tblContributors`.`CreationDate`',
		11 => '`tblContributors`.`ExpirationDate`',
		12 => '`tblContributors`.`LastAccessDate`',
		13 => '`tblContributors`.`Online`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`tblContributors`.`ID`" => "ID",
		"`tblContributors`.`FName`" => "FName",
		"`tblContributors`.`LName`" => "LName",
		"`tblContributors`.`Email`" => "Email",
		"`tblContributors`.`PW`" => "PW",
		"`tblContributors`.`Organization`" => "Organization",
		"`tblContributors`.`ScopeID`" => "ScopeID",
		"IF(    CHAR_LENGTH(`tblContributors1`.`ID`) || CHAR_LENGTH(`tblContributors1`.`LName`), CONCAT_WS('',   `tblContributors1`.`ID`, ': ', `tblContributors1`.`LName`), '') /* ParentID */" => "ParentID",
		"`tblContributors`.`AdminLevel`" => "AdminLevel",
		"if(`tblContributors`.`CreationDate`,date_format(`tblContributors`.`CreationDate`,'%m/%d/%Y'),'')" => "CreationDate",
		"if(`tblContributors`.`ExpirationDate`,date_format(`tblContributors`.`ExpirationDate`,'%m/%d/%Y'),'')" => "ExpirationDate",
		"if(`tblContributors`.`LastAccessDate`,date_format(`tblContributors`.`LastAccessDate`,'%m/%d/%Y'),'')" => "LastAccessDate",
		"`tblContributors`.`Online`" => "Online"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`tblContributors`.`ID`" => "ID",
		"`tblContributors`.`FName`" => "FName",
		"`tblContributors`.`LName`" => "LName",
		"`tblContributors`.`Email`" => "Email",
		"`tblContributors`.`PW`" => "PW",
		"`tblContributors`.`Organization`" => "Organization",
		"`tblContributors`.`ScopeID`" => "ScopeID",
		"IF(    CHAR_LENGTH(`tblContributors1`.`ID`) || CHAR_LENGTH(`tblContributors1`.`LName`), CONCAT_WS('',   `tblContributors1`.`ID`, ': ', `tblContributors1`.`LName`), '') /* ParentID */" => "ParentID",
		"`tblContributors`.`AdminLevel`" => "AdminLevel",
		"`tblContributors`.`CreationDate`" => "CreationDate",
		"`tblContributors`.`ExpirationDate`" => "ExpirationDate",
		"`tblContributors`.`LastAccessDate`" => "LastAccessDate",
		"`tblContributors`.`Online`" => "Online"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`tblContributors`.`ID`" => "ID",
		"`tblContributors`.`FName`" => "FName",
		"`tblContributors`.`LName`" => "LName",
		"`tblContributors`.`Email`" => "Email",
		"`tblContributors`.`PW`" => "PW",
		"`tblContributors`.`Organization`" => "Organization",
		"`tblContributors`.`ScopeID`" => "ScopeID",
		"IF(    CHAR_LENGTH(`tblContributors1`.`ID`) || CHAR_LENGTH(`tblContributors1`.`LName`), CONCAT_WS('',   `tblContributors1`.`ID`, ': ', `tblContributors1`.`LName`), '') /* ParentID */" => "ParentID",
		"`tblContributors`.`AdminLevel`" => "AdminLevel",
		"if(`tblContributors`.`CreationDate`,date_format(`tblContributors`.`CreationDate`,'%m/%d/%Y'),'')" => "CreationDate",
		"if(`tblContributors`.`ExpirationDate`,date_format(`tblContributors`.`ExpirationDate`,'%m/%d/%Y'),'')" => "ExpirationDate",
		"if(`tblContributors`.`LastAccessDate`,date_format(`tblContributors`.`LastAccessDate`,'%m/%d/%Y'),'')" => "LastAccessDate",
		"concat('<img src=\"', if(`tblContributors`.`Online`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "Online"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'ParentID' => 'ParentID');

	$x->QueryFrom="`tblContributors` LEFT JOIN `tblContributors` as tblContributors1 ON `tblContributors1`.`ID`=`tblContributors`.`ParentID` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "tblContributors_view.php";
	$x->RedirectAfterInsert = "tblContributors_view.php?SelectedID=#ID#";
	$x->TableTitle = "tblContributors";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`tblContributors`.`ID`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 50, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("ID", "FName", "LName", "Email", "PW", "Organization", "ScopeID", "ParentID", "AdminLevel", "CreationDate", "ExpirationDate", "LastAccessDate", "Online");
	$x->ColFieldName = array('ID', 'FName', 'LName', 'Email', 'PW', 'Organization', 'ScopeID', 'ParentID', 'AdminLevel', 'CreationDate', 'ExpirationDate', 'LastAccessDate', 'Online');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13);

	$x->Template = 'templates/tblContributors_templateTV.html';
	$x->SelectedTemplate = 'templates/tblContributors_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblContributors`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblContributors' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblContributors`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblContributors' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`tblContributors`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tblContributors_init
	$render=TRUE;
	if(function_exists('tblContributors_init')){
		$args=array();
		$render=tblContributors_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tblContributors_header
	$headerCode='';
	if(function_exists('tblContributors_header')){
		$args=array();
		$headerCode=tblContributors_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: tblContributors_footer
	$footerCode='';
	if(function_exists('tblContributors_footer')){
		$args=array();
		$footerCode=tblContributors_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>