<?php

// Data functions for table tblEntities

// This script and data application were generated by AppGini 5.30
// Download AppGini for free from http://bigprof.com/appgini/download/

function tblEntities_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('tblEntities');
	if(!$arrPerm[1]){
		return false;
	}

	$data['FName'] = makeSafe($_POST['FName']);
		if($data['FName'] == empty_lookup_value){ $data['FName'] = ''; }
	$data['LName'] = makeSafe($_POST['LName']);
		if($data['LName'] == empty_lookup_value){ $data['LName'] = ''; }
	$data['Birth'] = intval($_POST['BirthYear']) . '-' . intval($_POST['BirthMonth']) . '-' . intval($_POST['BirthDay']);
	$data['Birth'] = parseMySQLDate($data['Birth'], '');
	$data['Death'] = intval($_POST['DeathYear']) . '-' . intval($_POST['DeathMonth']) . '-' . intval($_POST['DeathDay']);
	$data['Death'] = parseMySQLDate($data['Death'], '');
	$data['DirectoryPath'] = makeSafe($_POST['DirectoryPath']);
		if($data['DirectoryPath'] == empty_lookup_value){ $data['DirectoryPath'] = ''; }
	$data['PrimaryGIID'] = makeSafe($_POST['PrimaryGIID']);
		if($data['PrimaryGIID'] == empty_lookup_value){ $data['PrimaryGIID'] = ''; }
	$data['BioDescrGIID'] = makeSafe($_POST['BioDescrGIID']);
		if($data['BioDescrGIID'] == empty_lookup_value){ $data['BioDescrGIID'] = ''; }
	$data['ImageURL'] = makeSafe($_POST['ImageURL']);
		if($data['ImageURL'] == empty_lookup_value){ $data['ImageURL'] = ''; }
	$data['ImageCaption'] = makeSafe($_POST['ImageCaption']);
		if($data['ImageCaption'] == empty_lookup_value){ $data['ImageCaption'] = ''; }
	$data['PrimaryAccessionID'] = makeSafe($_POST['PrimaryAccessionID']);
		if($data['PrimaryAccessionID'] == empty_lookup_value){ $data['PrimaryAccessionID'] = ''; }
	$data['TemplateID'] = makeSafe($_POST['TemplateID']);
		if($data['TemplateID'] == empty_lookup_value){ $data['TemplateID'] = ''; }
	$data['Online'] = makeSafe($_POST['Online']);
		if($data['Online'] == empty_lookup_value){ $data['Online'] = ''; }
	$data['CreationDate'] = intval($_POST['CreationDateYear']) . '-' . intval($_POST['CreationDateMonth']) . '-' . intval($_POST['CreationDateDay']);
	$data['CreationDate'] = parseMySQLDate($data['CreationDate'], '');
	$data['NewDesignationExpirationn'] = intval($_POST['NewDesignationExpirationnYear']) . '-' . intval($_POST['NewDesignationExpirationnMonth']) . '-' . intval($_POST['NewDesignationExpirationnDay']);
	$data['NewDesignationExpirationn'] = parseMySQLDate($data['NewDesignationExpirationn'], '');

	// hook: tblEntities_before_insert
	if(function_exists('tblEntities_before_insert')){
		$args=array();
		if(!tblEntities_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `tblEntities` set       `FName`=' . (($data['FName'] !== '' && $data['FName'] !== NULL) ? "'{$data['FName']}'" : 'NULL') . ', `LName`=' . (($data['LName'] !== '' && $data['LName'] !== NULL) ? "'{$data['LName']}'" : 'NULL') . ', `Birth`=' . (($data['Birth'] !== '' && $data['Birth'] !== NULL) ? "'{$data['Birth']}'" : 'NULL') . ', `Death`=' . (($data['Death'] !== '' && $data['Death'] !== NULL) ? "'{$data['Death']}'" : 'NULL') . ', `DirectoryPath`=' . (($data['DirectoryPath'] !== '' && $data['DirectoryPath'] !== NULL) ? "'{$data['DirectoryPath']}'" : 'NULL') . ', `PrimaryGIID`=' . (($data['PrimaryGIID'] !== '' && $data['PrimaryGIID'] !== NULL) ? "'{$data['PrimaryGIID']}'" : 'NULL') . ', `BioDescrGIID`=' . (($data['BioDescrGIID'] !== '' && $data['BioDescrGIID'] !== NULL) ? "'{$data['BioDescrGIID']}'" : 'NULL') . ', `ImageURL`=' . (($data['ImageURL'] !== '' && $data['ImageURL'] !== NULL) ? "'{$data['ImageURL']}'" : 'NULL') . ', `ImageCaption`=' . (($data['ImageCaption'] !== '' && $data['ImageCaption'] !== NULL) ? "'{$data['ImageCaption']}'" : 'NULL') . ', `PrimaryAccessionID`=' . (($data['PrimaryAccessionID'] !== '' && $data['PrimaryAccessionID'] !== NULL) ? "'{$data['PrimaryAccessionID']}'" : 'NULL') . ', `TemplateID`=' . (($data['TemplateID'] !== '' && $data['TemplateID'] !== NULL) ? "'{$data['TemplateID']}'" : 'NULL') . ', `Online`=' . (($data['Online'] !== '' && $data['Online'] !== NULL) ? "'{$data['Online']}'" : 'NULL') . ', `CreationDate`=' . (($data['CreationDate'] !== '' && $data['CreationDate'] !== NULL) ? "'{$data['CreationDate']}'" : 'NULL') . ', `NewDesignationExpirationn`=' . (($data['NewDesignationExpirationn'] !== '' && $data['NewDesignationExpirationn'] !== NULL) ? "'{$data['NewDesignationExpirationn']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"tblEntities_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=db_insert_id(db_link());

	// hook: tblEntities_after_insert
	if(function_exists('tblEntities_after_insert')){
		$res = sql("select * from `tblEntities` where `ID`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!tblEntities_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='tblEntities', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function tblEntities_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('tblEntities');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tblEntities' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tblEntities' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: tblEntities_before_delete
	if(function_exists('tblEntities_before_delete')){
		$args=array();
		if(!tblEntities_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: tblGalleries
	$res = sql("select `ID` from `tblEntities` where `ID`='$selected_id'", $eo);
	$ID = db_fetch_row($res);
	$rires = sql("select count(1) from `tblGalleries` where `EntityID`='".addslashes($ID[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tblGalleries", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tblGalleries", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input tabindex=\"2\" type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tblEntities_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input tabindex=\"2\" type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tblEntities_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: tblAccessions
	$res = sql("select `ID` from `tblEntities` where `ID`='$selected_id'", $eo);
	$ID = db_fetch_row($res);
	$rires = sql("select count(1) from `tblAccessions` where `EntityID`='".addslashes($ID[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tblAccessions", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tblAccessions", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input tabindex=\"2\" type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tblEntities_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input tabindex=\"2\" type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tblEntities_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `tblEntities` where `ID`='$selected_id'", $eo);

	// hook: tblEntities_after_delete
	if(function_exists('tblEntities_after_delete')){
		$args=array();
		tblEntities_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='tblEntities' and pkValue='$selected_id'", $eo);
}

function tblEntities_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('tblEntities');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tblEntities' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tblEntities' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['FName'] = makeSafe($_POST['FName']);
		if($data['FName'] == empty_lookup_value){ $data['FName'] = ''; }
	$data['LName'] = makeSafe($_POST['LName']);
		if($data['LName'] == empty_lookup_value){ $data['LName'] = ''; }
	$data['Birth'] = intval($_POST['BirthYear']) . '-' . intval($_POST['BirthMonth']) . '-' . intval($_POST['BirthDay']);
	$data['Birth'] = parseMySQLDate($data['Birth'], '');
	$data['Death'] = intval($_POST['DeathYear']) . '-' . intval($_POST['DeathMonth']) . '-' . intval($_POST['DeathDay']);
	$data['Death'] = parseMySQLDate($data['Death'], '');
	$data['DirectoryPath'] = makeSafe($_POST['DirectoryPath']);
		if($data['DirectoryPath'] == empty_lookup_value){ $data['DirectoryPath'] = ''; }
	$data['PrimaryGIID'] = makeSafe($_POST['PrimaryGIID']);
		if($data['PrimaryGIID'] == empty_lookup_value){ $data['PrimaryGIID'] = ''; }
	$data['BioDescrGIID'] = makeSafe($_POST['BioDescrGIID']);
		if($data['BioDescrGIID'] == empty_lookup_value){ $data['BioDescrGIID'] = ''; }
	$data['ImageURL'] = makeSafe($_POST['ImageURL']);
		if($data['ImageURL'] == empty_lookup_value){ $data['ImageURL'] = ''; }
	$data['ImageCaption'] = makeSafe($_POST['ImageCaption']);
		if($data['ImageCaption'] == empty_lookup_value){ $data['ImageCaption'] = ''; }
	$data['PrimaryAccessionID'] = makeSafe($_POST['PrimaryAccessionID']);
		if($data['PrimaryAccessionID'] == empty_lookup_value){ $data['PrimaryAccessionID'] = ''; }
	$data['TemplateID'] = makeSafe($_POST['TemplateID']);
		if($data['TemplateID'] == empty_lookup_value){ $data['TemplateID'] = ''; }
	$data['Online'] = makeSafe($_POST['Online']);
		if($data['Online'] == empty_lookup_value){ $data['Online'] = ''; }
	$data['CreationDate'] = intval($_POST['CreationDateYear']) . '-' . intval($_POST['CreationDateMonth']) . '-' . intval($_POST['CreationDateDay']);
	$data['CreationDate'] = parseMySQLDate($data['CreationDate'], '');
	$data['NewDesignationExpirationn'] = intval($_POST['NewDesignationExpirationnYear']) . '-' . intval($_POST['NewDesignationExpirationnMonth']) . '-' . intval($_POST['NewDesignationExpirationnDay']);
	$data['NewDesignationExpirationn'] = parseMySQLDate($data['NewDesignationExpirationn'], '');
	$data['selectedID']=makeSafe($selected_id);

	// hook: tblEntities_before_update
	if(function_exists('tblEntities_before_update')){
		$args=array();
		if(!tblEntities_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `tblEntities` set       `FName`=' . (($data['FName'] !== '' && $data['FName'] !== NULL) ? "'{$data['FName']}'" : 'NULL') . ', `LName`=' . (($data['LName'] !== '' && $data['LName'] !== NULL) ? "'{$data['LName']}'" : 'NULL') . ', `Birth`=' . (($data['Birth'] !== '' && $data['Birth'] !== NULL) ? "'{$data['Birth']}'" : 'NULL') . ', `Death`=' . (($data['Death'] !== '' && $data['Death'] !== NULL) ? "'{$data['Death']}'" : 'NULL') . ', `DirectoryPath`=' . (($data['DirectoryPath'] !== '' && $data['DirectoryPath'] !== NULL) ? "'{$data['DirectoryPath']}'" : 'NULL') . ', `PrimaryGIID`=' . (($data['PrimaryGIID'] !== '' && $data['PrimaryGIID'] !== NULL) ? "'{$data['PrimaryGIID']}'" : 'NULL') . ', `BioDescrGIID`=' . (($data['BioDescrGIID'] !== '' && $data['BioDescrGIID'] !== NULL) ? "'{$data['BioDescrGIID']}'" : 'NULL') . ', `ImageURL`=' . (($data['ImageURL'] !== '' && $data['ImageURL'] !== NULL) ? "'{$data['ImageURL']}'" : 'NULL') . ', `ImageCaption`=' . (($data['ImageCaption'] !== '' && $data['ImageCaption'] !== NULL) ? "'{$data['ImageCaption']}'" : 'NULL') . ', `PrimaryAccessionID`=' . (($data['PrimaryAccessionID'] !== '' && $data['PrimaryAccessionID'] !== NULL) ? "'{$data['PrimaryAccessionID']}'" : 'NULL') . ', `TemplateID`=' . (($data['TemplateID'] !== '' && $data['TemplateID'] !== NULL) ? "'{$data['TemplateID']}'" : 'NULL') . ', `Online`=' . (($data['Online'] !== '' && $data['Online'] !== NULL) ? "'{$data['Online']}'" : 'NULL') . ', `CreationDate`=' . (($data['CreationDate'] !== '' && $data['CreationDate'] !== NULL) ? "'{$data['CreationDate']}'" : 'NULL') . ', `NewDesignationExpirationn`=' . (($data['NewDesignationExpirationn'] !== '' && $data['NewDesignationExpirationn'] !== NULL) ? "'{$data['NewDesignationExpirationn']}'" : 'NULL') . " where `ID`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="tblEntities_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: tblEntities_after_update
	if(function_exists('tblEntities_after_update')){
		$res = sql("SELECT * FROM `tblEntities` WHERE `ID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['ID'];
		$args = array();
		if(!tblEntities_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='tblEntities' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function tblEntities_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('tblEntities');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Birth
	$combo_Birth = new DateCombo;
	$combo_Birth->DateFormat = "mdy";
	$combo_Birth->MinYear = 1900;
	$combo_Birth->MaxYear = 2100;
	$combo_Birth->DefaultDate = parseMySQLDate('', '');
	$combo_Birth->MonthNames = $Translation['month names'];
	$combo_Birth->NamePrefix = 'Birth';
	// combobox: Death
	$combo_Death = new DateCombo;
	$combo_Death->DateFormat = "mdy";
	$combo_Death->MinYear = 1900;
	$combo_Death->MaxYear = 2100;
	$combo_Death->DefaultDate = parseMySQLDate('', '');
	$combo_Death->MonthNames = $Translation['month names'];
	$combo_Death->NamePrefix = 'Death';
	// combobox: CreationDate
	$combo_CreationDate = new DateCombo;
	$combo_CreationDate->DateFormat = "mdy";
	$combo_CreationDate->MinYear = 1900;
	$combo_CreationDate->MaxYear = 2100;
	$combo_CreationDate->DefaultDate = parseMySQLDate('', '');
	$combo_CreationDate->MonthNames = $Translation['month names'];
	$combo_CreationDate->NamePrefix = 'CreationDate';
	// combobox: NewDesignationExpirationn
	$combo_NewDesignationExpirationn = new DateCombo;
	$combo_NewDesignationExpirationn->DateFormat = "mdy";
	$combo_NewDesignationExpirationn->MinYear = 1900;
	$combo_NewDesignationExpirationn->MaxYear = 2100;
	$combo_NewDesignationExpirationn->DefaultDate = parseMySQLDate('', '');
	$combo_NewDesignationExpirationn->MonthNames = $Translation['month names'];
	$combo_NewDesignationExpirationn->NamePrefix = 'NewDesignationExpirationn';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tblEntities' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tblEntities' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `tblEntities` where `ID`='".makeSafe($selected_id)."'", $eo);
		$row = db_fetch_array($res);
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_Birth->DefaultDate = $row['Birth'];
		$combo_Death->DefaultDate = $row['Death'];
		$combo_CreationDate->DefaultDate = $row['CreationDate'];
		$combo_NewDesignationExpirationn->DefaultDate = $row['NewDesignationExpirationn'];
	}else{
	}

	ob_start();
	?>

	<script>
		// initial lookup values
		
		jQuery(function() {
		});
	</script>
	<?php
	
	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/tblEntities_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/tblEntities_templateDV.html');
	}

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'tblEntitie details', $templateCode);
	$templateCode=str_replace('<%%RND1%%>', $rnd1, $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return tblEntities_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return tblEntities_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return tblEntities_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#FName').replaceWith('<p class=\"form-control-static\" id=\"FName\">' + (jQuery('#FName').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#LName').replaceWith('<p class=\"form-control-static\" id=\"LName\">' + (jQuery('#LName').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#Birth').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#BirthDay, #BirthMonth, #BirthYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Death').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#DeathDay, #DeathMonth, #DeathYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#DirectoryPath').replaceWith('<p class=\"form-control-static\" id=\"DirectoryPath\">' + (jQuery('#DirectoryPath').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#PrimaryGIID').replaceWith('<p class=\"form-control-static\" id=\"PrimaryGIID\">' + (jQuery('#PrimaryGIID').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#BioDescrGIID').replaceWith('<p class=\"form-control-static\" id=\"BioDescrGIID\">' + (jQuery('#BioDescrGIID').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#ImageURL').replaceWith('<p class=\"form-control-static\" id=\"ImageURL\">' + (jQuery('#ImageURL').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#ImageCaption').replaceWith('<p class=\"form-control-static\" id=\"ImageCaption\">' + (jQuery('#ImageCaption').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#PrimaryAccessionID').replaceWith('<p class=\"form-control-static\" id=\"PrimaryAccessionID\">' + (jQuery('#PrimaryAccessionID').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#TemplateID').replaceWith('<p class=\"form-control-static\" id=\"TemplateID\">' + (jQuery('#TemplateID').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#Online').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#CreationDate').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#CreationDateDay, #CreationDateMonth, #CreationDateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#NewDesignationExpirationn').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#NewDesignationExpirationnDay, #NewDesignationExpirationnMonth, #NewDesignationExpirationnYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(Birth)%%>', ($selected_id && !$arrPerm[3] ? '<p class="form-control-static">' . $combo_Birth->GetHTML(true) . '</p>' : $combo_Birth->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(Birth)%%>', $combo_Birth->GetHTML(true), $templateCode);
	$templateCode=str_replace('<%%COMBO(Death)%%>', ($selected_id && !$arrPerm[3] ? '<p class="form-control-static">' . $combo_Death->GetHTML(true) . '</p>' : $combo_Death->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(Death)%%>', $combo_Death->GetHTML(true), $templateCode);
	$templateCode=str_replace('<%%COMBO(CreationDate)%%>', ($selected_id && !$arrPerm[3] ? '<p class="form-control-static">' . $combo_CreationDate->GetHTML(true) . '</p>' : $combo_CreationDate->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(CreationDate)%%>', $combo_CreationDate->GetHTML(true), $templateCode);
	$templateCode=str_replace('<%%COMBO(NewDesignationExpirationn)%%>', ($selected_id && !$arrPerm[3] ? '<p class="form-control-static">' . $combo_NewDesignationExpirationn->GetHTML(true) . '</p>' : $combo_NewDesignationExpirationn->GetHTML()), $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(NewDesignationExpirationn)%%>', $combo_NewDesignationExpirationn->GetHTML(true), $templateCode);

	// process foreign key links
	if($selected_id){
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(ID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(FName)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(LName)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Birth)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Death)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(DirectoryPath)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(PrimaryGIID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(BioDescrGIID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ImageURL)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ImageCaption)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(PrimaryAccessionID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(TemplateID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Online)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(CreationDate)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(NewDesignationExpirationn)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(ID)%%>', htmlspecialchars($row['ID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ID)%%>', urlencode($urow['ID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(FName)%%>', htmlspecialchars($row['FName'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FName)%%>', urlencode($urow['FName']), $templateCode);
		$templateCode=str_replace('<%%VALUE(LName)%%>', htmlspecialchars($row['LName'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(LName)%%>', urlencode($urow['LName']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Birth)%%>', @date('m/d/Y', @strtotime(htmlspecialchars($row['Birth'], ENT_QUOTES))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Birth)%%>', urlencode(@date('m/d/Y', @strtotime(htmlspecialchars($urow['Birth'], ENT_QUOTES)))), $templateCode);
		$templateCode=str_replace('<%%VALUE(Death)%%>', @date('m/d/Y', @strtotime(htmlspecialchars($row['Death'], ENT_QUOTES))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Death)%%>', urlencode(@date('m/d/Y', @strtotime(htmlspecialchars($urow['Death'], ENT_QUOTES)))), $templateCode);
		$templateCode=str_replace('<%%VALUE(DirectoryPath)%%>', htmlspecialchars($row['DirectoryPath'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(DirectoryPath)%%>', urlencode($urow['DirectoryPath']), $templateCode);
		$templateCode=str_replace('<%%VALUE(PrimaryGIID)%%>', htmlspecialchars($row['PrimaryGIID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(PrimaryGIID)%%>', urlencode($urow['PrimaryGIID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(BioDescrGIID)%%>', htmlspecialchars($row['BioDescrGIID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(BioDescrGIID)%%>', urlencode($urow['BioDescrGIID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ImageURL)%%>', htmlspecialchars($row['ImageURL'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ImageURL)%%>', urlencode($urow['ImageURL']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ImageCaption)%%>', htmlspecialchars($row['ImageCaption'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ImageCaption)%%>', urlencode($urow['ImageCaption']), $templateCode);
		$templateCode=str_replace('<%%VALUE(PrimaryAccessionID)%%>', htmlspecialchars($row['PrimaryAccessionID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(PrimaryAccessionID)%%>', urlencode($urow['PrimaryAccessionID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(TemplateID)%%>', htmlspecialchars($row['TemplateID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(TemplateID)%%>', urlencode($urow['TemplateID']), $templateCode);
		$templateCode=str_replace('<%%CHECKED(Online)%%>', ($row['Online'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%VALUE(CreationDate)%%>', @date('m/d/Y', @strtotime(htmlspecialchars($row['CreationDate'], ENT_QUOTES))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CreationDate)%%>', urlencode(@date('m/d/Y', @strtotime(htmlspecialchars($urow['CreationDate'], ENT_QUOTES)))), $templateCode);
		$templateCode=str_replace('<%%VALUE(NewDesignationExpirationn)%%>', @date('m/d/Y', @strtotime(htmlspecialchars($row['NewDesignationExpirationn'], ENT_QUOTES))), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(NewDesignationExpirationn)%%>', urlencode(@date('m/d/Y', @strtotime(htmlspecialchars($urow['NewDesignationExpirationn'], ENT_QUOTES)))), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(ID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(FName)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(FName)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(LName)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(LName)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Birth)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Birth)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Death)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Death)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(DirectoryPath)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(DirectoryPath)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(PrimaryGIID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(PrimaryGIID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(BioDescrGIID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(BioDescrGIID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ImageURL)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ImageURL)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ImageCaption)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ImageCaption)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(PrimaryAccessionID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(PrimaryAccessionID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(TemplateID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(TemplateID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%CHECKED(Online)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(CreationDate)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CreationDate)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(NewDesignationExpirationn)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(NewDesignationExpirationn)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x']==''){
		$templateCode.="\n\n<script>jQuery(function(){\n";
		$arrTables=getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\tjQuery('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('#xs_{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('[id^=\"{$name}_plink\"]').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode.="<script>";
	$templateCode.="document.observe('dom:loaded', function() {";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: tblEntities_dv
	if(function_exists('tblEntities_dv')){
		$args=array();
		tblEntities_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>