<?php
// This script and data application were generated by AppGini 5.30
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/tblEntities.php");
	include("$currDir/tblEntities_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('tblEntities');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "tblEntities";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`tblEntities`.`ID`" => "ID",
		"`tblEntities`.`FName`" => "FName",
		"`tblEntities`.`LName`" => "LName",
		"if(`tblEntities`.`Birth`,date_format(`tblEntities`.`Birth`,'%m/%d/%Y'),'')" => "Birth",
		"if(`tblEntities`.`Death`,date_format(`tblEntities`.`Death`,'%m/%d/%Y'),'')" => "Death",
		"`tblEntities`.`DirectoryPath`" => "DirectoryPath",
		"`tblEntities`.`PrimaryGIID`" => "PrimaryGIID",
		"`tblEntities`.`BioDescrGIID`" => "BioDescrGIID",
		"`tblEntities`.`ImageURL`" => "ImageURL",
		"`tblEntities`.`ImageCaption`" => "ImageCaption",
		"`tblEntities`.`PrimaryAccessionID`" => "PrimaryAccessionID",
		"`tblEntities`.`TemplateID`" => "TemplateID",
		"concat('<img src=\"', if(`tblEntities`.`Online`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "Online",
		"if(`tblEntities`.`CreationDate`,date_format(`tblEntities`.`CreationDate`,'%m/%d/%Y'),'')" => "CreationDate",
		"if(`tblEntities`.`NewDesignationExpirationn`,date_format(`tblEntities`.`NewDesignationExpirationn`,'%m/%d/%Y'),'')" => "NewDesignationExpirationn"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`tblEntities`.`ID`',
		2 => 2,
		3 => 3,
		4 => '`tblEntities`.`Birth`',
		5 => '`tblEntities`.`Death`',
		6 => 6,
		7 => '`tblEntities`.`PrimaryGIID`',
		8 => '`tblEntities`.`BioDescrGIID`',
		9 => 9,
		10 => 10,
		11 => '`tblEntities`.`PrimaryAccessionID`',
		12 => '`tblEntities`.`TemplateID`',
		13 => '`tblEntities`.`Online`',
		14 => '`tblEntities`.`CreationDate`',
		15 => '`tblEntities`.`NewDesignationExpirationn`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`tblEntities`.`ID`" => "ID",
		"`tblEntities`.`FName`" => "FName",
		"`tblEntities`.`LName`" => "LName",
		"if(`tblEntities`.`Birth`,date_format(`tblEntities`.`Birth`,'%m/%d/%Y'),'')" => "Birth",
		"if(`tblEntities`.`Death`,date_format(`tblEntities`.`Death`,'%m/%d/%Y'),'')" => "Death",
		"`tblEntities`.`DirectoryPath`" => "DirectoryPath",
		"`tblEntities`.`PrimaryGIID`" => "PrimaryGIID",
		"`tblEntities`.`BioDescrGIID`" => "BioDescrGIID",
		"`tblEntities`.`ImageURL`" => "ImageURL",
		"`tblEntities`.`ImageCaption`" => "ImageCaption",
		"`tblEntities`.`PrimaryAccessionID`" => "PrimaryAccessionID",
		"`tblEntities`.`TemplateID`" => "TemplateID",
		"`tblEntities`.`Online`" => "Online",
		"if(`tblEntities`.`CreationDate`,date_format(`tblEntities`.`CreationDate`,'%m/%d/%Y'),'')" => "CreationDate",
		"if(`tblEntities`.`NewDesignationExpirationn`,date_format(`tblEntities`.`NewDesignationExpirationn`,'%m/%d/%Y'),'')" => "NewDesignationExpirationn"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`tblEntities`.`ID`" => "ID",
		"`tblEntities`.`FName`" => "FName",
		"`tblEntities`.`LName`" => "LName",
		"`tblEntities`.`Birth`" => "Birth",
		"`tblEntities`.`Death`" => "Death",
		"`tblEntities`.`DirectoryPath`" => "DirectoryPath",
		"`tblEntities`.`PrimaryGIID`" => "PrimaryGIID",
		"`tblEntities`.`BioDescrGIID`" => "BioDescrGIID",
		"`tblEntities`.`ImageURL`" => "ImageURL",
		"`tblEntities`.`ImageCaption`" => "ImageCaption",
		"`tblEntities`.`PrimaryAccessionID`" => "PrimaryAccessionID",
		"`tblEntities`.`TemplateID`" => "TemplateID",
		"`tblEntities`.`Online`" => "Online",
		"`tblEntities`.`CreationDate`" => "CreationDate",
		"`tblEntities`.`NewDesignationExpirationn`" => "NewDesignationExpirationn"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`tblEntities`.`ID`" => "ID",
		"`tblEntities`.`FName`" => "FName",
		"`tblEntities`.`LName`" => "LName",
		"if(`tblEntities`.`Birth`,date_format(`tblEntities`.`Birth`,'%m/%d/%Y'),'')" => "Birth",
		"if(`tblEntities`.`Death`,date_format(`tblEntities`.`Death`,'%m/%d/%Y'),'')" => "Death",
		"`tblEntities`.`DirectoryPath`" => "DirectoryPath",
		"`tblEntities`.`PrimaryGIID`" => "PrimaryGIID",
		"`tblEntities`.`BioDescrGIID`" => "BioDescrGIID",
		"`tblEntities`.`ImageURL`" => "ImageURL",
		"`tblEntities`.`ImageCaption`" => "ImageCaption",
		"`tblEntities`.`PrimaryAccessionID`" => "PrimaryAccessionID",
		"`tblEntities`.`TemplateID`" => "TemplateID",
		"concat('<img src=\"', if(`tblEntities`.`Online`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "Online",
		"if(`tblEntities`.`CreationDate`,date_format(`tblEntities`.`CreationDate`,'%m/%d/%Y'),'')" => "CreationDate",
		"if(`tblEntities`.`NewDesignationExpirationn`,date_format(`tblEntities`.`NewDesignationExpirationn`,'%m/%d/%Y'),'')" => "NewDesignationExpirationn"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`tblEntities` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "tblEntities_view.php";
	$x->RedirectAfterInsert = "tblEntities_view.php?SelectedID=#ID#";
	$x->TableTitle = "tblEntities";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`tblEntities`.`ID`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("ID", "FName", "LName", "Birth", "Death", "DirectoryPath", "PrimaryGIID", "BioDescrGIID", "ImageURL", "ImageCaption", "PrimaryAccessionID", "TemplateID", "Online", "CreationDate", "NewDesignationExpirationn");
	$x->ColFieldName = array('ID', 'FName', 'LName', 'Birth', 'Death', 'DirectoryPath', 'PrimaryGIID', 'BioDescrGIID', 'ImageURL', 'ImageCaption', 'PrimaryAccessionID', 'TemplateID', 'Online', 'CreationDate', 'NewDesignationExpirationn');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);

	$x->Template = 'templates/tblEntities_templateTV.html';
	$x->SelectedTemplate = 'templates/tblEntities_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblEntities`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblEntities' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblEntities`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblEntities' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`tblEntities`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tblEntities_init
	$render=TRUE;
	if(function_exists('tblEntities_init')){
		$args=array();
		$render=tblEntities_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tblEntities_header
	$headerCode='';
	if(function_exists('tblEntities_header')){
		$args=array();
		$headerCode=tblEntities_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: tblEntities_footer
	$footerCode='';
	if(function_exists('tblEntities_footer')){
		$args=array();
		$footerCode=tblEntities_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>