<?php
// This script and data application were generated by AppGini 5.30
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/tblGalleryItems.php");
	include("$currDir/tblGalleryItems_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('tblGalleryItems');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "tblGalleryItems";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`tblGalleryItems`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tblGalleries1`.`ID`) || CHAR_LENGTH(`tblGalleries1`.`Title`), CONCAT_WS('',   `tblGalleries1`.`ID`, ': ', `tblGalleries1`.`Title`), '') /* ParentGalleryID */" => "ParentGalleryID",
		"`tblGalleryItems`.`SubGalleryID`" => "SubGalleryID",
		"IF(    CHAR_LENGTH(`tblSubGalleryTypes1`.`ID`) || CHAR_LENGTH(`tblSubGalleryTypes1`.`Name`), CONCAT_WS('',   `tblSubGalleryTypes1`.`ID`, ': ', `tblSubGalleryTypes1`.`Name`), '') /* GalItemContentTypeID */" => "GIContentTypeID",
		"`tblGalleryItems`.`PageTitle`" => "PageTitle",
		"`tblGalleryItems`.`ThumbURL`" => "ThumbURL",
		"`tblGalleryItems`.`ThumbAltText`" => "ThumbAltText",
		"`tblGalleryItems`.`CSSClearBothAfter`" => "CSSClearBothAfter",
		"`tblGalleryItems`.`MenuTitle`" => "MenuTitle",
		"`tblGalleryItems`.`CaptionText`" => "CaptionText",
		"`tblGalleryItems`.`URL`" => "URL",
		"concat('<img src=\"', if(`tblGalleryItems`.`Online`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "Online",
		"`tblGalleryItems`.`HomepageFeaturedSort`" => "HomepageFeaturedSort",
		"`tblGalleryItems`.`Sort`" => "Sort",
		"concat('<img src=\"', if(`tblGalleryItems`.`BioDescrPage`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "BioDescrPage"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`tblGalleryItems`.`ID`',
		2 => 2,
		3 => '`tblGalleryItems`.`SubGalleryID`',
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`tblGalleryItems`.`CSSClearBothAfter`',
		9 => 9,
		10 => 10,
		11 => 11,
		12 => '`tblGalleryItems`.`Online`',
		13 => '`tblGalleryItems`.`HomepageFeaturedSort`',
		14 => '`tblGalleryItems`.`Sort`',
		15 => '`tblGalleryItems`.`BioDescrPage`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`tblGalleryItems`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tblGalleries1`.`ID`) || CHAR_LENGTH(`tblGalleries1`.`Title`), CONCAT_WS('',   `tblGalleries1`.`ID`, ': ', `tblGalleries1`.`Title`), '') /* ParentGalleryID */" => "ParentGalleryID",
		"`tblGalleryItems`.`SubGalleryID`" => "SubGalleryID",
		"IF(    CHAR_LENGTH(`tblSubGalleryTypes1`.`ID`) || CHAR_LENGTH(`tblSubGalleryTypes1`.`Name`), CONCAT_WS('',   `tblSubGalleryTypes1`.`ID`, ': ', `tblSubGalleryTypes1`.`Name`), '') /* GalItemContentTypeID */" => "GIContentTypeID",
		"`tblGalleryItems`.`PageTitle`" => "PageTitle",
		"`tblGalleryItems`.`ThumbURL`" => "ThumbURL",
		"`tblGalleryItems`.`ThumbAltText`" => "ThumbAltText",
		"`tblGalleryItems`.`CSSClearBothAfter`" => "CSSClearBothAfter",
		"`tblGalleryItems`.`MenuTitle`" => "MenuTitle",
		"`tblGalleryItems`.`CaptionText`" => "CaptionText",
		"`tblGalleryItems`.`URL`" => "URL",
		"`tblGalleryItems`.`Online`" => "Online",
		"`tblGalleryItems`.`HomepageFeaturedSort`" => "HomepageFeaturedSort",
		"`tblGalleryItems`.`Sort`" => "Sort",
		"`tblGalleryItems`.`BioDescrPage`" => "BioDescrPage"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`tblGalleryItems`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tblGalleries1`.`ID`) || CHAR_LENGTH(`tblGalleries1`.`Title`), CONCAT_WS('',   `tblGalleries1`.`ID`, ': ', `tblGalleries1`.`Title`), '') /* ParentGalleryID */" => "ParentGalleryID",
		"`tblGalleryItems`.`SubGalleryID`" => "SubGalleryID",
		"IF(    CHAR_LENGTH(`tblSubGalleryTypes1`.`ID`) || CHAR_LENGTH(`tblSubGalleryTypes1`.`Name`), CONCAT_WS('',   `tblSubGalleryTypes1`.`ID`, ': ', `tblSubGalleryTypes1`.`Name`), '') /* GalItemContentTypeID */" => "GalItemContentTypeID",
		"`tblGalleryItems`.`PageTitle`" => "PageTitle",
		"`tblGalleryItems`.`ThumbURL`" => "ThumbURL",
		"`tblGalleryItems`.`ThumbAltText`" => "ThumbAltText",
		"`tblGalleryItems`.`CSSClearBothAfter`" => "CSSClearBothAfter",
		"`tblGalleryItems`.`MenuTitle`" => "MenuTitle",
		"`tblGalleryItems`.`CaptionText`" => "CaptionText",
		"`tblGalleryItems`.`URL`" => "URL",
		"`tblGalleryItems`.`Online`" => "Online",
		"`tblGalleryItems`.`HomepageFeaturedSort`" => "HomepageFeaturedSort",
		"`tblGalleryItems`.`Sort`" => "Sort",
		"`tblGalleryItems`.`BioDescrPage`" => "BioDescrPage"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`tblGalleryItems`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tblGalleries1`.`ID`) || CHAR_LENGTH(`tblGalleries1`.`Title`), CONCAT_WS('',   `tblGalleries1`.`ID`, ': ', `tblGalleries1`.`Title`), '') /* ParentGalleryID */" => "ParentGalleryID",
		"`tblGalleryItems`.`SubGalleryID`" => "SubGalleryID",
		"IF(    CHAR_LENGTH(`tblSubGalleryTypes1`.`ID`) || CHAR_LENGTH(`tblSubGalleryTypes1`.`Name`), CONCAT_WS('',   `tblSubGalleryTypes1`.`ID`, ': ', `tblSubGalleryTypes1`.`Name`), '') /* GalItemContentTypeID */" => "GIContentTypeID",
		"`tblGalleryItems`.`PageTitle`" => "PageTitle",
		"`tblGalleryItems`.`ThumbURL`" => "ThumbURL",
		"`tblGalleryItems`.`ThumbAltText`" => "ThumbAltText",
		"`tblGalleryItems`.`CSSClearBothAfter`" => "CSSClearBothAfter",
		"`tblGalleryItems`.`MenuTitle`" => "MenuTitle",
		"`tblGalleryItems`.`CaptionText`" => "CaptionText",
		"`tblGalleryItems`.`URL`" => "URL",
		"concat('<img src=\"', if(`tblGalleryItems`.`Online`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "Online",
		"`tblGalleryItems`.`HomepageFeaturedSort`" => "HomepageFeaturedSort",
		"`tblGalleryItems`.`Sort`" => "Sort",
		"concat('<img src=\"', if(`tblGalleryItems`.`BioDescrPage`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "BioDescrPage"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'ParentGalleryID' => 'ParentGalleryID', 'GIContentTypeID' => 'GalItemContentTypeID');

	$x->QueryFrom="`tblGalleryItems` LEFT JOIN `tblGalleries` as tblGalleries1 ON `tblGalleries1`.`ID`=`tblGalleryItems`.`ParentGalleryID` LEFT JOIN `tblSubGalleryTypes` as tblSubGalleryTypes1 ON `tblSubGalleryTypes1`.`ID`=`tblGalleryItems`.`GIContentTypeID` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "tblGalleryItems_view.php";
	$x->RedirectAfterInsert = "tblGalleryItems_view.php?SelectedID=#ID#";
	$x->TableTitle = "tblGalleryItems";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`tblGalleryItems`.`ID`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("ID", "ParentGalleryID", "SubGalleryID", "GalItemContentTypeID", "PageTitle", "ThumbURL", "ThumbAltText", "CSSClearBothAfter", "MenuTitle", "CaptionText", "URL", "Online", "HomepageFeaturedSort", "Sort", "BioDescrPage");
	$x->ColFieldName = array('ID', 'ParentGalleryID', 'SubGalleryID', 'GIContentTypeID', 'PageTitle', 'ThumbURL', 'ThumbAltText', 'CSSClearBothAfter', 'MenuTitle', 'CaptionText', 'URL', 'Online', 'HomepageFeaturedSort', 'Sort', 'BioDescrPage');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);

	$x->Template = 'templates/tblGalleryItems_templateTV.html';
	$x->SelectedTemplate = 'templates/tblGalleryItems_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblGalleryItems`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblGalleryItems' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblGalleryItems`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblGalleryItems' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`tblGalleryItems`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tblGalleryItems_init
	$render=TRUE;
	if(function_exists('tblGalleryItems_init')){
		$args=array();
		$render=tblGalleryItems_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tblGalleryItems_header
	$headerCode='';
	if(function_exists('tblGalleryItems_header')){
		$args=array();
		$headerCode=tblGalleryItems_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: tblGalleryItems_footer
	$footerCode='';
	if(function_exists('tblGalleryItems_footer')){
		$args=array();
		$footerCode=tblGalleryItems_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>