<?php

// Data functions for table tblGalleries

// This script and data application were generated by AppGini 5.30
// Download AppGini for free from http://bigprof.com/appgini/download/

function tblGalleries_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('tblGalleries');
	if(!$arrPerm[1]){
		return false;
	}

	$data['Title'] = makeSafe($_POST['Title']);
		if($data['Title'] == empty_lookup_value){ $data['Title'] = ''; }
	$data['Summary'] = makeSafe($_POST['Summary']);
		if($data['Summary'] == empty_lookup_value){ $data['Summary'] = ''; }
	$data['HeaderImageURL'] = makeSafe($_POST['HeaderImageURL']);
		if($data['HeaderImageURL'] == empty_lookup_value){ $data['HeaderImageURL'] = ''; }
	$data['HeaderImageLinkURL'] = makeSafe($_POST['HeaderImageLinkURL']);
		if($data['HeaderImageLinkURL'] == empty_lookup_value){ $data['HeaderImageLinkURL'] = ''; }
	$data['EntityID'] = makeSafe($_POST['EntityID']);
		if($data['EntityID'] == empty_lookup_value){ $data['EntityID'] = ''; }
	$data['GIContentTypeID'] = makeSafe($_POST['GIContentTypeID']);
		if($data['GIContentTypeID'] == empty_lookup_value){ $data['GIContentTypeID'] = ''; }
	$data['ContributorID'] = makeSafe($_POST['ContributorID']);
		if($data['ContributorID'] == empty_lookup_value){ $data['ContributorID'] = ''; }
	$data['ThumbURL'] = makeSafe($_POST['ThumbURL']);
		if($data['ThumbURL'] == empty_lookup_value){ $data['ThumbURL'] = ''; }
	$data['CaptionText'] = br2nl(makeSafe($_POST['CaptionText']));
	$data['TemplateURL'] = makeSafe($_POST['TemplateURL']);
		if($data['TemplateURL'] == empty_lookup_value){ $data['TemplateURL'] = ''; }
	$data['ItemDisplayLimit'] = makeSafe($_POST['ItemDisplayLimit']);
		if($data['ItemDisplayLimit'] == empty_lookup_value){ $data['ItemDisplayLimit'] = ''; }
	$data['URL'] = makeSafe($_POST['URL']);
		if($data['URL'] == empty_lookup_value){ $data['URL'] = ''; }
	$data['EmbedShowPlayer'] = makeSafe($_POST['EmbedShowPlayer']);
		if($data['EmbedShowPlayer'] == empty_lookup_value){ $data['EmbedShowPlayer'] = ''; }
	$data['Online'] = makeSafe($_POST['Online']);
		if($data['Online'] == empty_lookup_value){ $data['Online'] = ''; }
	$data['Sort'] = makeSafe($_POST['Sort']);
		if($data['Sort'] == empty_lookup_value){ $data['Sort'] = ''; }

	// hook: tblGalleries_before_insert
	if(function_exists('tblGalleries_before_insert')){
		$args=array();
		if(!tblGalleries_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `tblGalleries` set       `Title`=' . (($data['Title'] !== '' && $data['Title'] !== NULL) ? "'{$data['Title']}'" : 'NULL') . ', `Summary`=' . (($data['Summary'] !== '' && $data['Summary'] !== NULL) ? "'{$data['Summary']}'" : 'NULL') . ', `HeaderImageURL`=' . (($data['HeaderImageURL'] !== '' && $data['HeaderImageURL'] !== NULL) ? "'{$data['HeaderImageURL']}'" : 'NULL') . ', `HeaderImageLinkURL`=' . (($data['HeaderImageLinkURL'] !== '' && $data['HeaderImageLinkURL'] !== NULL) ? "'{$data['HeaderImageLinkURL']}'" : 'NULL') . ', `EntityID`=' . (($data['EntityID'] !== '' && $data['EntityID'] !== NULL) ? "'{$data['EntityID']}'" : 'NULL') . ', `GIContentTypeID`=' . (($data['GIContentTypeID'] !== '' && $data['GIContentTypeID'] !== NULL) ? "'{$data['GIContentTypeID']}'" : 'NULL') . ', `ContributorID`=' . (($data['ContributorID'] !== '' && $data['ContributorID'] !== NULL) ? "'{$data['ContributorID']}'" : 'NULL') . ', `ThumbURL`=' . (($data['ThumbURL'] !== '' && $data['ThumbURL'] !== NULL) ? "'{$data['ThumbURL']}'" : 'NULL') . ', `CaptionText`=' . (($data['CaptionText'] !== '' && $data['CaptionText'] !== NULL) ? "'{$data['CaptionText']}'" : 'NULL') . ', `TemplateURL`=' . (($data['TemplateURL'] !== '' && $data['TemplateURL'] !== NULL) ? "'{$data['TemplateURL']}'" : 'NULL') . ', `ItemDisplayLimit`=' . (($data['ItemDisplayLimit'] !== '' && $data['ItemDisplayLimit'] !== NULL) ? "'{$data['ItemDisplayLimit']}'" : 'NULL') . ', `URL`=' . (($data['URL'] !== '' && $data['URL'] !== NULL) ? "'{$data['URL']}'" : 'NULL') . ', `EmbedShowPlayer`=' . (($data['EmbedShowPlayer'] !== '' && $data['EmbedShowPlayer'] !== NULL) ? "'{$data['EmbedShowPlayer']}'" : 'NULL') . ', `Online`=' . (($data['Online'] !== '' && $data['Online'] !== NULL) ? "'{$data['Online']}'" : 'NULL') . ', `Sort`=' . (($data['Sort'] !== '' && $data['Sort'] !== NULL) ? "'{$data['Sort']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"tblGalleries_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=db_insert_id(db_link());

	// hook: tblGalleries_after_insert
	if(function_exists('tblGalleries_after_insert')){
		$res = sql("select * from `tblGalleries` where `ID`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!tblGalleries_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='tblGalleries', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function tblGalleries_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('tblGalleries');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tblGalleries' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tblGalleries' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: tblGalleries_before_delete
	if(function_exists('tblGalleries_before_delete')){
		$args=array();
		if(!tblGalleries_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: tblGalleryItems
	$res = sql("select `ID` from `tblGalleries` where `ID`='$selected_id'", $eo);
	$ID = db_fetch_row($res);
	$rires = sql("select count(1) from `tblGalleryItems` where `ParentGalleryID`='".addslashes($ID[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tblGalleryItems", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "tblGalleryItems", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input tabindex=\"2\" type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='tblGalleries_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input tabindex=\"2\" type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='tblGalleries_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `tblGalleries` where `ID`='$selected_id'", $eo);

	// hook: tblGalleries_after_delete
	if(function_exists('tblGalleries_after_delete')){
		$args=array();
		tblGalleries_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='tblGalleries' and pkValue='$selected_id'", $eo);
}

function tblGalleries_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('tblGalleries');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tblGalleries' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tblGalleries' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Title'] = makeSafe($_POST['Title']);
		if($data['Title'] == empty_lookup_value){ $data['Title'] = ''; }
	$data['Summary'] = makeSafe($_POST['Summary']);
		if($data['Summary'] == empty_lookup_value){ $data['Summary'] = ''; }
	$data['HeaderImageURL'] = makeSafe($_POST['HeaderImageURL']);
		if($data['HeaderImageURL'] == empty_lookup_value){ $data['HeaderImageURL'] = ''; }
	$data['HeaderImageLinkURL'] = makeSafe($_POST['HeaderImageLinkURL']);
		if($data['HeaderImageLinkURL'] == empty_lookup_value){ $data['HeaderImageLinkURL'] = ''; }
	$data['EntityID'] = makeSafe($_POST['EntityID']);
		if($data['EntityID'] == empty_lookup_value){ $data['EntityID'] = ''; }
	$data['GIContentTypeID'] = makeSafe($_POST['GIContentTypeID']);
		if($data['GIContentTypeID'] == empty_lookup_value){ $data['GIContentTypeID'] = ''; }
	$data['ContributorID'] = makeSafe($_POST['ContributorID']);
		if($data['ContributorID'] == empty_lookup_value){ $data['ContributorID'] = ''; }
	$data['ThumbURL'] = makeSafe($_POST['ThumbURL']);
		if($data['ThumbURL'] == empty_lookup_value){ $data['ThumbURL'] = ''; }
	$data['CaptionText'] = br2nl(makeSafe($_POST['CaptionText']));
	$data['TemplateURL'] = makeSafe($_POST['TemplateURL']);
		if($data['TemplateURL'] == empty_lookup_value){ $data['TemplateURL'] = ''; }
	$data['ItemDisplayLimit'] = makeSafe($_POST['ItemDisplayLimit']);
		if($data['ItemDisplayLimit'] == empty_lookup_value){ $data['ItemDisplayLimit'] = ''; }
	$data['URL'] = makeSafe($_POST['URL']);
		if($data['URL'] == empty_lookup_value){ $data['URL'] = ''; }
	$data['EmbedShowPlayer'] = makeSafe($_POST['EmbedShowPlayer']);
		if($data['EmbedShowPlayer'] == empty_lookup_value){ $data['EmbedShowPlayer'] = ''; }
	$data['Online'] = makeSafe($_POST['Online']);
		if($data['Online'] == empty_lookup_value){ $data['Online'] = ''; }
	$data['Sort'] = makeSafe($_POST['Sort']);
		if($data['Sort'] == empty_lookup_value){ $data['Sort'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: tblGalleries_before_update
	if(function_exists('tblGalleries_before_update')){
		$args=array();
		if(!tblGalleries_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `tblGalleries` set       `Title`=' . (($data['Title'] !== '' && $data['Title'] !== NULL) ? "'{$data['Title']}'" : 'NULL') . ', `Summary`=' . (($data['Summary'] !== '' && $data['Summary'] !== NULL) ? "'{$data['Summary']}'" : 'NULL') . ', `HeaderImageURL`=' . (($data['HeaderImageURL'] !== '' && $data['HeaderImageURL'] !== NULL) ? "'{$data['HeaderImageURL']}'" : 'NULL') . ', `HeaderImageLinkURL`=' . (($data['HeaderImageLinkURL'] !== '' && $data['HeaderImageLinkURL'] !== NULL) ? "'{$data['HeaderImageLinkURL']}'" : 'NULL') . ', `EntityID`=' . (($data['EntityID'] !== '' && $data['EntityID'] !== NULL) ? "'{$data['EntityID']}'" : 'NULL') . ', `GIContentTypeID`=' . (($data['GIContentTypeID'] !== '' && $data['GIContentTypeID'] !== NULL) ? "'{$data['GIContentTypeID']}'" : 'NULL') . ', `ContributorID`=' . (($data['ContributorID'] !== '' && $data['ContributorID'] !== NULL) ? "'{$data['ContributorID']}'" : 'NULL') . ', `ThumbURL`=' . (($data['ThumbURL'] !== '' && $data['ThumbURL'] !== NULL) ? "'{$data['ThumbURL']}'" : 'NULL') . ', `CaptionText`=' . (($data['CaptionText'] !== '' && $data['CaptionText'] !== NULL) ? "'{$data['CaptionText']}'" : 'NULL') . ', `TemplateURL`=' . (($data['TemplateURL'] !== '' && $data['TemplateURL'] !== NULL) ? "'{$data['TemplateURL']}'" : 'NULL') . ', `ItemDisplayLimit`=' . (($data['ItemDisplayLimit'] !== '' && $data['ItemDisplayLimit'] !== NULL) ? "'{$data['ItemDisplayLimit']}'" : 'NULL') . ', `URL`=' . (($data['URL'] !== '' && $data['URL'] !== NULL) ? "'{$data['URL']}'" : 'NULL') . ', `EmbedShowPlayer`=' . (($data['EmbedShowPlayer'] !== '' && $data['EmbedShowPlayer'] !== NULL) ? "'{$data['EmbedShowPlayer']}'" : 'NULL') . ', `Online`=' . (($data['Online'] !== '' && $data['Online'] !== NULL) ? "'{$data['Online']}'" : 'NULL') . ', `Sort`=' . (($data['Sort'] !== '' && $data['Sort'] !== NULL) ? "'{$data['Sort']}'" : 'NULL') . " where `ID`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="tblGalleries_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: tblGalleries_after_update
	if(function_exists('tblGalleries_after_update')){
		$res = sql("SELECT * FROM `tblGalleries` WHERE `ID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['ID'];
		$args = array();
		if(!tblGalleries_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='tblGalleries' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function tblGalleries_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('tblGalleries');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_EntityID = thisOr(undo_magic_quotes($_REQUEST['filterer_EntityID']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: EntityID
	$combo_EntityID = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tblGalleries' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tblGalleries' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `tblGalleries` where `ID`='".makeSafe($selected_id)."'", $eo);
		$row = db_fetch_array($res);
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_EntityID->SelectedData = $row['EntityID'];
	}else{
		$combo_EntityID->SelectedData = $filterer_EntityID;
	}
	$combo_EntityID->HTML = '<span id="EntityID-container' . $rnd1 . '"></span><input type="hidden" name="EntityID" id="EntityID' . $rnd1 . '">';
	$combo_EntityID->MatchText = '<span id="EntityID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="EntityID" id="EntityID' . $rnd1 . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_EntityID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['EntityID'] : $filterer_EntityID); ?>"};
		
		jQuery(function() {
			EntityID_reload__RAND__();
		});
		function EntityID_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#EntityID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_EntityID__RAND__.value, t: 'tblGalleries', f: 'EntityID' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="EntityID"]').val(resp.results[0].id);
						jQuery('[id=EntityID-container-readonly__RAND__]').html('<span id="EntityID-match-text">' + resp.results[0].text + '</span>');


						if(typeof(EntityID_update_autofills__RAND__) == 'function') EntityID_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'tblGalleries', f: 'EntityID' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_EntityID__RAND__.value = e.added.id;
				current_EntityID__RAND__.text = e.added.text;
				jQuery('[name="EntityID"]').val(e.added.id);


				if(typeof(EntityID_update_autofills__RAND__) == 'function') EntityID_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_EntityID__RAND__.value, t: 'tblGalleries', f: 'EntityID' }
			}).done(function(resp){
				jQuery('[id=EntityID-container__RAND__], [id=EntityID-container-readonly__RAND__]').html('<span id="EntityID-match-text">' + resp.results[0].text + '</span>');

				if(typeof(EntityID_update_autofills__RAND__) == 'function') EntityID_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php
	
	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/tblGalleries_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/tblGalleries_templateDV.html');
	}

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'tblGalleries details', $templateCode);
	$templateCode=str_replace('<%%RND1%%>', $rnd1, $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return tblGalleries_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return tblGalleries_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return tblGalleries_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#Title').replaceWith('<p class=\"form-control-static\" id=\"Title\">' + (jQuery('#Title').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#Summary').replaceWith('<p class=\"form-control-static\" id=\"Summary\">' + (jQuery('#Summary').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#HeaderImageURL').replaceWith('<p class=\"form-control-static\" id=\"HeaderImageURL\">' + (jQuery('#HeaderImageURL').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#HeaderImageLinkURL').replaceWith('<p class=\"form-control-static\" id=\"HeaderImageLinkURL\">' + (jQuery('#HeaderImageLinkURL').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#EntityID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#EntityID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#GIContentTypeID').replaceWith('<p class=\"form-control-static\" id=\"GIContentTypeID\">' + (jQuery('#GIContentTypeID').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#ContributorID').replaceWith('<p class=\"form-control-static\" id=\"ContributorID\">' + (jQuery('#ContributorID').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#ThumbURL').replaceWith('<p class=\"form-control-static\" id=\"ThumbURL\">' + (jQuery('#ThumbURL').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#CaptionText').replaceWith('<p class=\"form-control-static\" id=\"CaptionText\">' + (jQuery('#CaptionText').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#TemplateURL').replaceWith('<p class=\"form-control-static\" id=\"TemplateURL\">' + (jQuery('#TemplateURL').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#ItemDisplayLimit').replaceWith('<p class=\"form-control-static\" id=\"ItemDisplayLimit\">' + (jQuery('#ItemDisplayLimit').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#URL').replaceWith('<p class=\"form-control-static\" id=\"URL\">' + (jQuery('#URL').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#EmbedShowPlayer').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#Online').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#Sort').replaceWith('<p class=\"form-control-static\" id=\"Sort\">' + (jQuery('#Sort').val() || '') + '</p>');\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(EntityID)%%>', $combo_EntityID->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(EntityID)%%>', $combo_EntityID->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(EntityID)%%>', urlencode($combo_EntityID->MatchText), $templateCode);

	// process foreign key links
	if($selected_id){
		$templateCode=str_replace('<%%PLINK(EntityID)%%>', ($combo_EntityID->SelectedData ? "<span id=\"tblEntities_plink1\" class=\"hidden\"><a class=\"btn btn-default\" href=\"tblEntities_view.php?SelectedID=" . urlencode($combo_EntityID->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(ID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Title)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Summary)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(HeaderImageURL)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(HeaderImageLinkURL)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(EntityID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(GIContentTypeID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ContributorID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ThumbURL)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(CaptionText)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(TemplateURL)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ItemDisplayLimit)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(URL)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(EmbedShowPlayer)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Online)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Sort)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(ID)%%>', htmlspecialchars($row['ID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ID)%%>', urlencode($urow['ID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Title)%%>', htmlspecialchars($row['Title'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Title)%%>', urlencode($urow['Title']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Summary)%%>', htmlspecialchars($row['Summary'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Summary)%%>', urlencode($urow['Summary']), $templateCode);
		$templateCode=str_replace('<%%VALUE(HeaderImageURL)%%>', htmlspecialchars($row['HeaderImageURL'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(HeaderImageURL)%%>', urlencode($urow['HeaderImageURL']), $templateCode);
		$templateCode=str_replace('<%%VALUE(HeaderImageLinkURL)%%>', htmlspecialchars($row['HeaderImageLinkURL'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(HeaderImageLinkURL)%%>', urlencode($urow['HeaderImageLinkURL']), $templateCode);
		$templateCode=str_replace('<%%VALUE(EntityID)%%>', htmlspecialchars($row['EntityID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(EntityID)%%>', urlencode($urow['EntityID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(GIContentTypeID)%%>', htmlspecialchars($row['GIContentTypeID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(GIContentTypeID)%%>', urlencode($urow['GIContentTypeID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ContributorID)%%>', htmlspecialchars($row['ContributorID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ContributorID)%%>', urlencode($urow['ContributorID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ThumbURL)%%>', htmlspecialchars($row['ThumbURL'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ThumbURL)%%>', urlencode($urow['ThumbURL']), $templateCode);
		if($dvprint){
			$templateCode = str_replace('<%%VALUE(CaptionText)%%>', nl2br(htmlspecialchars($row['CaptionText'], ENT_QUOTES)), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(CaptionText)%%>', htmlspecialchars($row['CaptionText'], ENT_QUOTES), $templateCode);
		}
		$templateCode=str_replace('<%%URLVALUE(CaptionText)%%>', urlencode($urow['CaptionText']), $templateCode);
		$templateCode=str_replace('<%%VALUE(TemplateURL)%%>', htmlspecialchars($row['TemplateURL'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(TemplateURL)%%>', urlencode($urow['TemplateURL']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ItemDisplayLimit)%%>', htmlspecialchars($row['ItemDisplayLimit'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ItemDisplayLimit)%%>', urlencode($urow['ItemDisplayLimit']), $templateCode);
		$templateCode=str_replace('<%%VALUE(URL)%%>', htmlspecialchars($row['URL'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(URL)%%>', urlencode($urow['URL']), $templateCode);
		$templateCode=str_replace('<%%CHECKED(EmbedShowPlayer)%%>', ($row['EmbedShowPlayer'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%CHECKED(Online)%%>', ($row['Online'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%VALUE(Sort)%%>', htmlspecialchars($row['Sort'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Sort)%%>', urlencode($urow['Sort']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(ID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Title)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Title)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Summary)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Summary)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(HeaderImageURL)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(HeaderImageURL)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(HeaderImageLinkURL)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(HeaderImageLinkURL)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(EntityID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(EntityID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(GIContentTypeID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(GIContentTypeID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ContributorID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ContributorID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ThumbURL)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ThumbURL)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(CaptionText)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CaptionText)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(TemplateURL)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(TemplateURL)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ItemDisplayLimit)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ItemDisplayLimit)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(URL)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(URL)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%CHECKED(EmbedShowPlayer)%%>', '', $templateCode);
		$templateCode=str_replace('<%%CHECKED(Online)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Sort)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Sort)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x']==''){
		$templateCode.="\n\n<script>jQuery(function(){\n";
		$arrTables=getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\tjQuery('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('#xs_{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('[id^=\"{$name}_plink\"]').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode.="<script>";
	$templateCode.="document.observe('dom:loaded', function() {";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: tblGalleries_dv
	if(function_exists('tblGalleries_dv')){
		$args=array();
		tblGalleries_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>