<?php

// Data functions for table tblGalleryItems

// This script and data application were generated by AppGini 5.30
// Download AppGini for free from http://bigprof.com/appgini/download/

function tblGalleryItems_insert(){
	global $Translation;

	if($_GET['insert_x']!=''){$_POST=$_GET;}

	// mm: can member insert record?
	$arrPerm=getTablePermissions('tblGalleryItems');
	if(!$arrPerm[1]){
		return false;
	}

	$data['ParentGalleryID'] = makeSafe($_POST['ParentGalleryID']);
		if($data['ParentGalleryID'] == empty_lookup_value){ $data['ParentGalleryID'] = ''; }
	$data['SubGalleryID'] = makeSafe($_POST['SubGalleryID']);
		if($data['SubGalleryID'] == empty_lookup_value){ $data['SubGalleryID'] = ''; }
	$data['GIContentTypeID'] = makeSafe($_POST['GIContentTypeID']);
		if($data['GIContentTypeID'] == empty_lookup_value){ $data['GIContentTypeID'] = ''; }
	$data['PageTitle'] = makeSafe($_POST['PageTitle']);
		if($data['PageTitle'] == empty_lookup_value){ $data['PageTitle'] = ''; }
	$data['ThumbURL'] = makeSafe($_POST['ThumbURL']);
		if($data['ThumbURL'] == empty_lookup_value){ $data['ThumbURL'] = ''; }
	$data['ThumbAltText'] = makeSafe($_POST['ThumbAltText']);
		if($data['ThumbAltText'] == empty_lookup_value){ $data['ThumbAltText'] = ''; }
	$data['CSSClearBothAfter'] = makeSafe($_POST['CSSClearBothAfter']);
		if($data['CSSClearBothAfter'] == empty_lookup_value){ $data['CSSClearBothAfter'] = ''; }
	$data['MenuTitle'] = makeSafe($_POST['MenuTitle']);
		if($data['MenuTitle'] == empty_lookup_value){ $data['MenuTitle'] = ''; }
	$data['CaptionText'] = makeSafe($_POST['CaptionText']);
		if($data['CaptionText'] == empty_lookup_value){ $data['CaptionText'] = ''; }
	$data['URL'] = makeSafe($_POST['URL']);
		if($data['URL'] == empty_lookup_value){ $data['URL'] = ''; }
	$data['Online'] = makeSafe($_POST['Online']);
		if($data['Online'] == empty_lookup_value){ $data['Online'] = ''; }
	$data['HomepageFeaturedSort'] = makeSafe($_POST['HomepageFeaturedSort']);
		if($data['HomepageFeaturedSort'] == empty_lookup_value){ $data['HomepageFeaturedSort'] = ''; }
	$data['Sort'] = makeSafe($_POST['Sort']);
		if($data['Sort'] == empty_lookup_value){ $data['Sort'] = ''; }
	$data['BioDescrPage'] = makeSafe($_POST['BioDescrPage']);
		if($data['BioDescrPage'] == empty_lookup_value){ $data['BioDescrPage'] = ''; }
	if($data['CSSClearBothAfter'] == '') $data['CSSClearBothAfter'] = "-1";

	// hook: tblGalleryItems_before_insert
	if(function_exists('tblGalleryItems_before_insert')){
		$args=array();
		if(!tblGalleryItems_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('insert into `tblGalleryItems` set       `ParentGalleryID`=' . (($data['ParentGalleryID'] !== '' && $data['ParentGalleryID'] !== NULL) ? "'{$data['ParentGalleryID']}'" : 'NULL') . ', `SubGalleryID`=' . (($data['SubGalleryID'] !== '' && $data['SubGalleryID'] !== NULL) ? "'{$data['SubGalleryID']}'" : 'NULL') . ', `GIContentTypeID`=' . (($data['GIContentTypeID'] !== '' && $data['GIContentTypeID'] !== NULL) ? "'{$data['GIContentTypeID']}'" : 'NULL') . ', `PageTitle`=' . (($data['PageTitle'] !== '' && $data['PageTitle'] !== NULL) ? "'{$data['PageTitle']}'" : 'NULL') . ', `ThumbURL`=' . (($data['ThumbURL'] !== '' && $data['ThumbURL'] !== NULL) ? "'{$data['ThumbURL']}'" : 'NULL') . ', `ThumbAltText`=' . (($data['ThumbAltText'] !== '' && $data['ThumbAltText'] !== NULL) ? "'{$data['ThumbAltText']}'" : 'NULL') . ', `CSSClearBothAfter`=' . (($data['CSSClearBothAfter'] !== '' && $data['CSSClearBothAfter'] !== NULL) ? "'{$data['CSSClearBothAfter']}'" : 'NULL') . ', `MenuTitle`=' . (($data['MenuTitle'] !== '' && $data['MenuTitle'] !== NULL) ? "'{$data['MenuTitle']}'" : 'NULL') . ', `CaptionText`=' . (($data['CaptionText'] !== '' && $data['CaptionText'] !== NULL) ? "'{$data['CaptionText']}'" : 'NULL') . ', `URL`=' . (($data['URL'] !== '' && $data['URL'] !== NULL) ? "'{$data['URL']}'" : 'NULL') . ', `Online`=' . (($data['Online'] !== '' && $data['Online'] !== NULL) ? "'{$data['Online']}'" : 'NULL') . ', `HomepageFeaturedSort`=' . (($data['HomepageFeaturedSort'] !== '' && $data['HomepageFeaturedSort'] !== NULL) ? "'{$data['HomepageFeaturedSort']}'" : 'NULL') . ', `Sort`=' . (($data['Sort'] !== '' && $data['Sort'] !== NULL) ? "'{$data['Sort']}'" : 'NULL') . ', `BioDescrPage`=' . (($data['BioDescrPage'] !== '' && $data['BioDescrPage'] !== NULL) ? "'{$data['BioDescrPage']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"tblGalleryItems_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID=db_insert_id(db_link());

	// hook: tblGalleryItems_after_insert
	if(function_exists('tblGalleryItems_after_insert')){
		$res = sql("select * from `tblGalleryItems` where `ID`='" . makeSafe($recID) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID);
		$args=array();
		if(!tblGalleryItems_after_insert($data, getMemberInfo(), $args)){ return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID); }
	}

	// mm: save ownership data
	sql("insert into membership_userrecords set tableName='tblGalleryItems', pkValue='$recID', memberID='".getLoggedMemberID()."', dateAdded='".time()."', dateUpdated='".time()."', groupID='".getLoggedGroupID()."'", $eo);

	return (get_magic_quotes_gpc() ? stripslashes($recID) : $recID);
}

function tblGalleryItems_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('tblGalleryItems');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tblGalleryItems' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tblGalleryItems' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: tblGalleryItems_before_delete
	if(function_exists('tblGalleryItems_before_delete')){
		$args=array();
		if(!tblGalleryItems_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `tblGalleryItems` where `ID`='$selected_id'", $eo);

	// hook: tblGalleryItems_after_delete
	if(function_exists('tblGalleryItems_after_delete')){
		$args=array();
		tblGalleryItems_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='tblGalleryItems' and pkValue='$selected_id'", $eo);
}

function tblGalleryItems_update($selected_id){
	global $Translation;

	if($_GET['update_x']!=''){$_POST=$_GET;}

	// mm: can member edit record?
	$arrPerm=getTablePermissions('tblGalleryItems');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tblGalleryItems' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tblGalleryItems' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['ParentGalleryID'] = makeSafe($_POST['ParentGalleryID']);
		if($data['ParentGalleryID'] == empty_lookup_value){ $data['ParentGalleryID'] = ''; }
	$data['SubGalleryID'] = makeSafe($_POST['SubGalleryID']);
		if($data['SubGalleryID'] == empty_lookup_value){ $data['SubGalleryID'] = ''; }
	$data['GIContentTypeID'] = makeSafe($_POST['GIContentTypeID']);
		if($data['GIContentTypeID'] == empty_lookup_value){ $data['GIContentTypeID'] = ''; }
	$data['PageTitle'] = makeSafe($_POST['PageTitle']);
		if($data['PageTitle'] == empty_lookup_value){ $data['PageTitle'] = ''; }
	$data['ThumbURL'] = makeSafe($_POST['ThumbURL']);
		if($data['ThumbURL'] == empty_lookup_value){ $data['ThumbURL'] = ''; }
	$data['ThumbAltText'] = makeSafe($_POST['ThumbAltText']);
		if($data['ThumbAltText'] == empty_lookup_value){ $data['ThumbAltText'] = ''; }
	$data['CSSClearBothAfter'] = makeSafe($_POST['CSSClearBothAfter']);
		if($data['CSSClearBothAfter'] == empty_lookup_value){ $data['CSSClearBothAfter'] = ''; }
	$data['MenuTitle'] = makeSafe($_POST['MenuTitle']);
		if($data['MenuTitle'] == empty_lookup_value){ $data['MenuTitle'] = ''; }
	$data['CaptionText'] = makeSafe($_POST['CaptionText']);
		if($data['CaptionText'] == empty_lookup_value){ $data['CaptionText'] = ''; }
	$data['URL'] = makeSafe($_POST['URL']);
		if($data['URL'] == empty_lookup_value){ $data['URL'] = ''; }
	$data['Online'] = makeSafe($_POST['Online']);
		if($data['Online'] == empty_lookup_value){ $data['Online'] = ''; }
	$data['HomepageFeaturedSort'] = makeSafe($_POST['HomepageFeaturedSort']);
		if($data['HomepageFeaturedSort'] == empty_lookup_value){ $data['HomepageFeaturedSort'] = ''; }
	$data['Sort'] = makeSafe($_POST['Sort']);
		if($data['Sort'] == empty_lookup_value){ $data['Sort'] = ''; }
	$data['BioDescrPage'] = makeSafe($_POST['BioDescrPage']);
		if($data['BioDescrPage'] == empty_lookup_value){ $data['BioDescrPage'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: tblGalleryItems_before_update
	if(function_exists('tblGalleryItems_before_update')){
		$args=array();
		if(!tblGalleryItems_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `tblGalleryItems` set       `ParentGalleryID`=' . (($data['ParentGalleryID'] !== '' && $data['ParentGalleryID'] !== NULL) ? "'{$data['ParentGalleryID']}'" : 'NULL') . ', `SubGalleryID`=' . (($data['SubGalleryID'] !== '' && $data['SubGalleryID'] !== NULL) ? "'{$data['SubGalleryID']}'" : 'NULL') . ', `GIContentTypeID`=' . (($data['GIContentTypeID'] !== '' && $data['GIContentTypeID'] !== NULL) ? "'{$data['GIContentTypeID']}'" : 'NULL') . ', `PageTitle`=' . (($data['PageTitle'] !== '' && $data['PageTitle'] !== NULL) ? "'{$data['PageTitle']}'" : 'NULL') . ', `ThumbURL`=' . (($data['ThumbURL'] !== '' && $data['ThumbURL'] !== NULL) ? "'{$data['ThumbURL']}'" : 'NULL') . ', `ThumbAltText`=' . (($data['ThumbAltText'] !== '' && $data['ThumbAltText'] !== NULL) ? "'{$data['ThumbAltText']}'" : 'NULL') . ', `CSSClearBothAfter`=' . (($data['CSSClearBothAfter'] !== '' && $data['CSSClearBothAfter'] !== NULL) ? "'{$data['CSSClearBothAfter']}'" : 'NULL') . ', `MenuTitle`=' . (($data['MenuTitle'] !== '' && $data['MenuTitle'] !== NULL) ? "'{$data['MenuTitle']}'" : 'NULL') . ', `CaptionText`=' . (($data['CaptionText'] !== '' && $data['CaptionText'] !== NULL) ? "'{$data['CaptionText']}'" : 'NULL') . ', `URL`=' . (($data['URL'] !== '' && $data['URL'] !== NULL) ? "'{$data['URL']}'" : 'NULL') . ', `Online`=' . (($data['Online'] !== '' && $data['Online'] !== NULL) ? "'{$data['Online']}'" : 'NULL') . ', `HomepageFeaturedSort`=' . (($data['HomepageFeaturedSort'] !== '' && $data['HomepageFeaturedSort'] !== NULL) ? "'{$data['HomepageFeaturedSort']}'" : 'NULL') . ', `Sort`=' . (($data['Sort'] !== '' && $data['Sort'] !== NULL) ? "'{$data['Sort']}'" : 'NULL') . ', `BioDescrPage`=' . (($data['BioDescrPage'] !== '' && $data['BioDescrPage'] !== NULL) ? "'{$data['BioDescrPage']}'" : 'NULL') . " where `ID`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="tblGalleryItems_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: tblGalleryItems_after_update
	if(function_exists('tblGalleryItems_after_update')){
		$res = sql("SELECT * FROM `tblGalleryItems` WHERE `ID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['ID'];
		$args = array();
		if(!tblGalleryItems_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='tblGalleryItems' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function tblGalleryItems_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('tblGalleryItems');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_ParentGalleryID = thisOr(undo_magic_quotes($_REQUEST['filterer_ParentGalleryID']), '');
	$filterer_GIContentTypeID = thisOr(undo_magic_quotes($_REQUEST['filterer_GIContentTypeID']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: ParentGalleryID
	$combo_ParentGalleryID = new DataCombo;
	// combobox: GIContentTypeID
	$combo_GIContentTypeID = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='tblGalleryItems' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='tblGalleryItems' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `tblGalleryItems` where `ID`='".makeSafe($selected_id)."'", $eo);
		$row = db_fetch_array($res);
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_ParentGalleryID->SelectedData = $row['ParentGalleryID'];
		$combo_GIContentTypeID->SelectedData = $row['GIContentTypeID'];
	}else{
		$combo_ParentGalleryID->SelectedData = $filterer_ParentGalleryID;
		$combo_GIContentTypeID->SelectedData = $filterer_GIContentTypeID;
	}
	$combo_ParentGalleryID->HTML = '<span id="ParentGalleryID-container' . $rnd1 . '"></span><input type="hidden" name="ParentGalleryID" id="ParentGalleryID' . $rnd1 . '">';
	$combo_ParentGalleryID->MatchText = '<span id="ParentGalleryID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="ParentGalleryID" id="ParentGalleryID' . $rnd1 . '">';
	$combo_GIContentTypeID->HTML = '<span id="GIContentTypeID-container' . $rnd1 . '"></span><input type="hidden" name="GIContentTypeID" id="GIContentTypeID' . $rnd1 . '">';
	$combo_GIContentTypeID->MatchText = '<span id="GIContentTypeID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="GIContentTypeID" id="GIContentTypeID' . $rnd1 . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		var current_ParentGalleryID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['ParentGalleryID'] : $filterer_ParentGalleryID); ?>"};
		var current_GIContentTypeID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['GIContentTypeID'] : $filterer_GIContentTypeID); ?>"};
		
		jQuery(function() {
			ParentGalleryID_reload__RAND__();
			GIContentTypeID_reload__RAND__();
		});
		function ParentGalleryID_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#ParentGalleryID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_ParentGalleryID__RAND__.value, t: 'tblGalleryItems', f: 'ParentGalleryID' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="ParentGalleryID"]').val(resp.results[0].id);
						jQuery('[id=ParentGalleryID-container-readonly__RAND__]').html('<span id="ParentGalleryID-match-text">' + resp.results[0].text + '</span>');


						if(typeof(ParentGalleryID_update_autofills__RAND__) == 'function') ParentGalleryID_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'tblGalleryItems', f: 'ParentGalleryID' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_ParentGalleryID__RAND__.value = e.added.id;
				current_ParentGalleryID__RAND__.text = e.added.text;
				jQuery('[name="ParentGalleryID"]').val(e.added.id);


				if(typeof(ParentGalleryID_update_autofills__RAND__) == 'function') ParentGalleryID_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_ParentGalleryID__RAND__.value, t: 'tblGalleryItems', f: 'ParentGalleryID' }
			}).done(function(resp){
				jQuery('[id=ParentGalleryID-container__RAND__], [id=ParentGalleryID-container-readonly__RAND__]').html('<span id="ParentGalleryID-match-text">' + resp.results[0].text + '</span>');

				if(typeof(ParentGalleryID_update_autofills__RAND__) == 'function') ParentGalleryID_update_autofills__RAND__();
			});
		<?php } ?>

		}
		function GIContentTypeID_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			jQuery("#GIContentTypeID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					jQuery.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: current_GIContentTypeID__RAND__.value, t: 'tblGalleryItems', f: 'GIContentTypeID' }
					}).done(function(resp){
						c({
							id: resp.results[0].id,
							text: resp.results[0].text
						});
						jQuery('[name="GIContentTypeID"]').val(resp.results[0].id);
						jQuery('[id=GIContentTypeID-container-readonly__RAND__]').html('<span id="GIContentTypeID-match-text">' + resp.results[0].text + '</span>');


						if(typeof(GIContentTypeID_update_autofills__RAND__) == 'function') GIContentTypeID_update_autofills__RAND__();
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'tblGalleryItems', f: 'GIContentTypeID' }; },
					results: function(resp, page){ return resp; }
				}
			}).on('change', function(e){
				current_GIContentTypeID__RAND__.value = e.added.id;
				current_GIContentTypeID__RAND__.text = e.added.text;
				jQuery('[name="GIContentTypeID"]').val(e.added.id);


				if(typeof(GIContentTypeID_update_autofills__RAND__) == 'function') GIContentTypeID_update_autofills__RAND__();
			});
		<?php }else{ ?>

			jQuery.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: current_GIContentTypeID__RAND__.value, t: 'tblGalleryItems', f: 'GIContentTypeID' }
			}).done(function(resp){
				jQuery('[id=GIContentTypeID-container__RAND__], [id=GIContentTypeID-container-readonly__RAND__]').html('<span id="GIContentTypeID-match-text">' + resp.results[0].text + '</span>');

				if(typeof(GIContentTypeID_update_autofills__RAND__) == 'function') GIContentTypeID_update_autofills__RAND__();
			});
		<?php } ?>

		}
	</script>
	<?php
	
	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$templateCode = @file_get_contents('./templates/tblGalleryItems_templateDVP.html');
	}else{
		$templateCode = @file_get_contents('./templates/tblGalleryItems_templateDV.html');
	}

	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'tblGalleryItem details', $templateCode);
	$templateCode=str_replace('<%%RND1%%>', $rnd1, $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return tblGalleryItems_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return tblGalleryItems_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return tblGalleryItems_validateData();"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button tabindex="2" type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#ParentGalleryID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#ParentGalleryID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#SubGalleryID').replaceWith('<p class=\"form-control-static\" id=\"SubGalleryID\">' + (jQuery('#SubGalleryID').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#GIContentTypeID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#GIContentTypeID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#PageTitle').replaceWith('<p class=\"form-control-static\" id=\"PageTitle\">' + (jQuery('#PageTitle').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#ThumbURL').replaceWith('<p class=\"form-control-static\" id=\"ThumbURL\">' + (jQuery('#ThumbURL').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#ThumbAltText').replaceWith('<p class=\"form-control-static\" id=\"ThumbAltText\">' + (jQuery('#ThumbAltText').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#CSSClearBothAfter').replaceWith('<p class=\"form-control-static\" id=\"CSSClearBothAfter\">' + (jQuery('#CSSClearBothAfter').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#MenuTitle').replaceWith('<p class=\"form-control-static\" id=\"MenuTitle\">' + (jQuery('#MenuTitle').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#CaptionText').replaceWith('<p class=\"form-control-static\" id=\"CaptionText\">' + (jQuery('#CaptionText').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#URL').replaceWith('<p class=\"form-control-static\" id=\"URL\">' + (jQuery('#URL').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#Online').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#HomepageFeaturedSort').replaceWith('<p class=\"form-control-static\" id=\"HomepageFeaturedSort\">' + (jQuery('#HomepageFeaturedSort').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#Sort').replaceWith('<p class=\"form-control-static\" id=\"Sort\">' + (jQuery('#Sort').val() || '') + '</p>');\n";
		$jsReadOnly .= "\tjQuery('#BioDescrPage').prop('disabled', true);\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(ParentGalleryID)%%>', $combo_ParentGalleryID->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(ParentGalleryID)%%>', $combo_ParentGalleryID->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(ParentGalleryID)%%>', urlencode($combo_ParentGalleryID->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(GIContentTypeID)%%>', $combo_GIContentTypeID->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(GIContentTypeID)%%>', $combo_GIContentTypeID->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(GIContentTypeID)%%>', urlencode($combo_GIContentTypeID->MatchText), $templateCode);

	// process foreign key links
	if($selected_id){
		$templateCode=str_replace('<%%PLINK(ParentGalleryID)%%>', ($combo_ParentGalleryID->SelectedData ? "<span id=\"tblGalleries_plink1\" class=\"hidden\"><a class=\"btn btn-default\" href=\"tblGalleries_view.php?SelectedID=" . urlencode($combo_ParentGalleryID->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
		$templateCode=str_replace('<%%PLINK(GIContentTypeID)%%>', ($combo_GIContentTypeID->SelectedData ? "<span id=\"tblSubGalleryTypes_plink2\" class=\"hidden\"><a class=\"btn btn-default\" href=\"tblSubGalleryTypes_view.php?SelectedID=" . urlencode($combo_GIContentTypeID->SelectedData) . "\"><i class=\"glyphicon glyphicon-search\"></i></a></span>" : ''), $templateCode);
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(ID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ParentGalleryID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(SubGalleryID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(GIContentTypeID)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(PageTitle)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ThumbURL)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ThumbAltText)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(CSSClearBothAfter)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(MenuTitle)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(CaptionText)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(URL)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Online)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(HomepageFeaturedSort)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Sort)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(BioDescrPage)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(ID)%%>', htmlspecialchars($row['ID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ID)%%>', urlencode($urow['ID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ParentGalleryID)%%>', htmlspecialchars($row['ParentGalleryID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ParentGalleryID)%%>', urlencode($urow['ParentGalleryID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(SubGalleryID)%%>', htmlspecialchars($row['SubGalleryID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(SubGalleryID)%%>', urlencode($urow['SubGalleryID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(GIContentTypeID)%%>', htmlspecialchars($row['GIContentTypeID'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(GIContentTypeID)%%>', urlencode($urow['GIContentTypeID']), $templateCode);
		$templateCode=str_replace('<%%VALUE(PageTitle)%%>', htmlspecialchars($row['PageTitle'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(PageTitle)%%>', urlencode($urow['PageTitle']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ThumbURL)%%>', htmlspecialchars($row['ThumbURL'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ThumbURL)%%>', urlencode($urow['ThumbURL']), $templateCode);
		$templateCode=str_replace('<%%VALUE(ThumbAltText)%%>', htmlspecialchars($row['ThumbAltText'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ThumbAltText)%%>', urlencode($urow['ThumbAltText']), $templateCode);
		$templateCode=str_replace('<%%VALUE(CSSClearBothAfter)%%>', htmlspecialchars($row['CSSClearBothAfter'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CSSClearBothAfter)%%>', urlencode($urow['CSSClearBothAfter']), $templateCode);
		$templateCode=str_replace('<%%VALUE(MenuTitle)%%>', htmlspecialchars($row['MenuTitle'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MenuTitle)%%>', urlencode($urow['MenuTitle']), $templateCode);
		$templateCode=str_replace('<%%VALUE(CaptionText)%%>', htmlspecialchars($row['CaptionText'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CaptionText)%%>', urlencode($urow['CaptionText']), $templateCode);
		$templateCode=str_replace('<%%VALUE(URL)%%>', htmlspecialchars($row['URL'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(URL)%%>', urlencode($urow['URL']), $templateCode);
		$templateCode=str_replace('<%%CHECKED(Online)%%>', ($row['Online'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%VALUE(HomepageFeaturedSort)%%>', htmlspecialchars($row['HomepageFeaturedSort'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(HomepageFeaturedSort)%%>', urlencode($urow['HomepageFeaturedSort']), $templateCode);
		$templateCode=str_replace('<%%VALUE(Sort)%%>', htmlspecialchars($row['Sort'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Sort)%%>', urlencode($urow['Sort']), $templateCode);
		$templateCode=str_replace('<%%CHECKED(BioDescrPage)%%>', ($row['BioDescrPage'] ? "checked" : ""), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(ID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ParentGalleryID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ParentGalleryID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(SubGalleryID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(SubGalleryID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(GIContentTypeID)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(GIContentTypeID)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(PageTitle)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(PageTitle)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ThumbURL)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ThumbURL)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ThumbAltText)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ThumbAltText)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(CSSClearBothAfter)%%>', '-1', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CSSClearBothAfter)%%>', urlencode('-1'), $templateCode);
		$templateCode=str_replace('<%%VALUE(MenuTitle)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(MenuTitle)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(CaptionText)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(CaptionText)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(URL)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(URL)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%CHECKED(Online)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(HomepageFeaturedSort)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(HomepageFeaturedSort)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(Sort)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(Sort)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%CHECKED(BioDescrPage)%%>', '', $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_POST['dvprint_x']==''){
		$templateCode.="\n\n<script>jQuery(function(){\n";
		$arrTables=getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\tjQuery('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('#xs_{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\tjQuery('[id^=\"{$name}_plink\"]').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode.="<script>";
	$templateCode.="document.observe('dom:loaded', function() {";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode=preg_replace('/blank.gif" rel="lightbox\[.*?\]"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	// hook: tblGalleryItems_dv
	if(function_exists('tblGalleryItems_dv')){
		$args=array();
		tblGalleryItems_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>