<?php
// This script and data application were generated by AppGini 5.30
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/tblGalleries.php");
	include("$currDir/tblGalleries_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('tblGalleries');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "tblGalleries";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`tblGalleries`.`ID`" => "ID",
		"`tblGalleries`.`Title`" => "Title",
		"`tblGalleries`.`Summary`" => "Summary",
		"`tblGalleries`.`HeaderImageURL`" => "HeaderImageURL",
		"`tblGalleries`.`HeaderImageLinkURL`" => "HeaderImageLinkURL",
		"IF(    CHAR_LENGTH(`tblEntities1`.`ID`) || CHAR_LENGTH(`tblEntities1`.`LName`), CONCAT_WS('',   `tblEntities1`.`ID`, ': ', `tblEntities1`.`LName`), '') /* EntityID */" => "EntityID",
		"`tblGalleries`.`GIContentTypeID`" => "GIContentTypeID",
		"`tblGalleries`.`ContributorID`" => "ContributorID",
		"`tblGalleries`.`ThumbURL`" => "ThumbURL",
		"`tblGalleries`.`CaptionText`" => "CaptionText",
		"`tblGalleries`.`TemplateURL`" => "TemplateURL",
		"`tblGalleries`.`ItemDisplayLimit`" => "ItemDisplayLimit",
		"`tblGalleries`.`URL`" => "URL",
		"concat('<img src=\"', if(`tblGalleries`.`EmbedShowPlayer`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "EmbedShowPlayer",
		"concat('<img src=\"', if(`tblGalleries`.`Online`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "Online",
		"`tblGalleries`.`Sort`" => "Sort"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`tblGalleries`.`ID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`tblGalleries`.`GIContentTypeID`',
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => '`tblGalleries`.`ItemDisplayLimit`',
		13 => 13,
		14 => '`tblGalleries`.`EmbedShowPlayer`',
		15 => '`tblGalleries`.`Online`',
		16 => '`tblGalleries`.`Sort`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`tblGalleries`.`ID`" => "ID",
		"`tblGalleries`.`Title`" => "Title",
		"`tblGalleries`.`Summary`" => "Summary",
		"`tblGalleries`.`HeaderImageURL`" => "HeaderImageURL",
		"`tblGalleries`.`HeaderImageLinkURL`" => "HeaderImageLinkURL",
		"IF(    CHAR_LENGTH(`tblEntities1`.`ID`) || CHAR_LENGTH(`tblEntities1`.`LName`), CONCAT_WS('',   `tblEntities1`.`ID`, ': ', `tblEntities1`.`LName`), '') /* EntityID */" => "EntityID",
		"`tblGalleries`.`GIContentTypeID`" => "GIContentTypeID",
		"`tblGalleries`.`ContributorID`" => "ContributorID",
		"`tblGalleries`.`ThumbURL`" => "ThumbURL",
		"`tblGalleries`.`CaptionText`" => "CaptionText",
		"`tblGalleries`.`TemplateURL`" => "TemplateURL",
		"`tblGalleries`.`ItemDisplayLimit`" => "ItemDisplayLimit",
		"`tblGalleries`.`URL`" => "URL",
		"`tblGalleries`.`EmbedShowPlayer`" => "EmbedShowPlayer",
		"`tblGalleries`.`Online`" => "Online",
		"`tblGalleries`.`Sort`" => "Sort"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`tblGalleries`.`ID`" => "ID",
		"`tblGalleries`.`Title`" => "Title",
		"`tblGalleries`.`Summary`" => "Summary",
		"`tblGalleries`.`HeaderImageURL`" => "HeaderImageURL",
		"`tblGalleries`.`HeaderImageLinkURL`" => "HeaderImageLinkURL",
		"IF(    CHAR_LENGTH(`tblEntities1`.`ID`) || CHAR_LENGTH(`tblEntities1`.`LName`), CONCAT_WS('',   `tblEntities1`.`ID`, ': ', `tblEntities1`.`LName`), '') /* EntityID */" => "EntityID",
		"`tblGalleries`.`GIContentTypeID`" => "GIContentTypeID",
		"`tblGalleries`.`ContributorID`" => "ContributorID",
		"`tblGalleries`.`ThumbURL`" => "ThumbURL",
		"`tblGalleries`.`CaptionText`" => "CaptionText",
		"`tblGalleries`.`TemplateURL`" => "TemplateURL",
		"`tblGalleries`.`ItemDisplayLimit`" => "ItemDisplayLimit",
		"`tblGalleries`.`URL`" => "URL",
		"`tblGalleries`.`EmbedShowPlayer`" => "EmbedShowPlayer",
		"`tblGalleries`.`Online`" => "Online",
		"`tblGalleries`.`Sort`" => "Sort"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`tblGalleries`.`ID`" => "ID",
		"`tblGalleries`.`Title`" => "Title",
		"`tblGalleries`.`Summary`" => "Summary",
		"`tblGalleries`.`HeaderImageURL`" => "HeaderImageURL",
		"`tblGalleries`.`HeaderImageLinkURL`" => "HeaderImageLinkURL",
		"IF(    CHAR_LENGTH(`tblEntities1`.`ID`) || CHAR_LENGTH(`tblEntities1`.`LName`), CONCAT_WS('',   `tblEntities1`.`ID`, ': ', `tblEntities1`.`LName`), '') /* EntityID */" => "EntityID",
		"`tblGalleries`.`GIContentTypeID`" => "GIContentTypeID",
		"`tblGalleries`.`ContributorID`" => "ContributorID",
		"`tblGalleries`.`ThumbURL`" => "ThumbURL",
		"`tblGalleries`.`CaptionText`" => "CaptionText",
		"`tblGalleries`.`TemplateURL`" => "TemplateURL",
		"`tblGalleries`.`ItemDisplayLimit`" => "ItemDisplayLimit",
		"`tblGalleries`.`URL`" => "URL",
		"concat('<img src=\"', if(`tblGalleries`.`EmbedShowPlayer`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "EmbedShowPlayer",
		"concat('<img src=\"', if(`tblGalleries`.`Online`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "Online",
		"`tblGalleries`.`Sort`" => "Sort"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'EntityID' => 'EntityID');

	$x->QueryFrom="`tblGalleries` LEFT JOIN `tblEntities` as tblEntities1 ON `tblEntities1`.`ID`=`tblGalleries`.`EntityID` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 0;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "tblGalleries_view.php";
	$x->RedirectAfterInsert = "tblGalleries_view.php?SelectedID=#ID#";
	$x->TableTitle = "tblGalleries";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`tblGalleries`.`ID`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("ID", "Title", "Summary", "HeaderImageURL", "HeaderImageLinkURL", "EntityID", "GIContentTypeID", "ContributorID", "ThumbURL", "CaptionText", "TemplateURL", "ItemDisplayLimit", "URL", "EmbedShowPlayer", "Online", "Sort");
	$x->ColFieldName = array('ID', 'Title', 'Summary', 'HeaderImageURL', 'HeaderImageLinkURL', 'EntityID', 'GIContentTypeID', 'ContributorID', 'ThumbURL', 'CaptionText', 'TemplateURL', 'ItemDisplayLimit', 'URL', 'EmbedShowPlayer', 'Online', 'Sort');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16);

	$x->Template = 'templates/tblGalleries_templateTV.html';
	$x->SelectedTemplate = 'templates/tblGalleries_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblGalleries`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblGalleries' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblGalleries`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblGalleries' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`tblGalleries`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tblGalleries_init
	$render=TRUE;
	if(function_exists('tblGalleries_init')){
		$args=array();
		$render=tblGalleries_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tblGalleries_header
	$headerCode='';
	if(function_exists('tblGalleries_header')){
		$args=array();
		$headerCode=tblGalleries_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: tblGalleries_footer
	$footerCode='';
	if(function_exists('tblGalleries_footer')){
		$args=array();
		$footerCode=tblGalleries_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>