<?php
// This script and data application were generated by AppGini 5.30
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/tblNavMenu.php");
	include("$currDir/tblNavMenu_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('tblNavMenu');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "tblNavMenu";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`tblNavMenu`.`ID`" => "ID",
		"`tblNavMenu`.`Label`" => "Label",
		"`tblNavMenu`.`HierarchyLevel`" => "HierarchyLevel",
		"`tblNavMenu`.`URL`" => "URL",
		"concat('<img src=\"', if(`tblNavMenu`.`Online`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "Online",
		"`tblNavMenu`.`Sort`" => "Sort"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`tblNavMenu`.`ID`',
		2 => 2,
		3 => '`tblNavMenu`.`HierarchyLevel`',
		4 => 4,
		5 => '`tblNavMenu`.`Online`',
		6 => '`tblNavMenu`.`Sort`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`tblNavMenu`.`ID`" => "ID",
		"`tblNavMenu`.`Label`" => "Label",
		"`tblNavMenu`.`HierarchyLevel`" => "HierarchyLevel",
		"`tblNavMenu`.`URL`" => "URL",
		"`tblNavMenu`.`Online`" => "Online",
		"`tblNavMenu`.`Sort`" => "Sort"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`tblNavMenu`.`ID`" => "ID",
		"`tblNavMenu`.`Label`" => "Label",
		"`tblNavMenu`.`HierarchyLevel`" => "HierarchyLevel",
		"`tblNavMenu`.`URL`" => "URL",
		"`tblNavMenu`.`Online`" => "Online",
		"`tblNavMenu`.`Sort`" => "Sort"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`tblNavMenu`.`ID`" => "ID",
		"`tblNavMenu`.`Label`" => "Label",
		"`tblNavMenu`.`HierarchyLevel`" => "HierarchyLevel",
		"`tblNavMenu`.`URL`" => "URL",
		"concat('<img src=\"', if(`tblNavMenu`.`Online`, 'checked.gif', 'checkednot.gif'), '\" border=\"0\" />')" => "Online",
		"`tblNavMenu`.`Sort`" => "Sort"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`tblNavMenu` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "tblNavMenu_view.php";
	$x->RedirectAfterInsert = "tblNavMenu_view.php?SelectedID=#ID#";
	$x->TableTitle = "tblNavMenu";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`tblNavMenu`.`ID`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("ID", "Label", "HierarchyLevel", "URL", "Online", "Sort");
	$x->ColFieldName = array('ID', 'Label', 'HierarchyLevel', 'URL', 'Online', 'Sort');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6);

	$x->Template = 'templates/tblNavMenu_templateTV.html';
	$x->SelectedTemplate = 'templates/tblNavMenu_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblNavMenu`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblNavMenu' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblNavMenu`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblNavMenu' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`tblNavMenu`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tblNavMenu_init
	$render=TRUE;
	if(function_exists('tblNavMenu_init')){
		$args=array();
		$render=tblNavMenu_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tblNavMenu_header
	$headerCode='';
	if(function_exists('tblNavMenu_header')){
		$args=array();
		$headerCode=tblNavMenu_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: tblNavMenu_footer
	$footerCode='';
	if(function_exists('tblNavMenu_footer')){
		$args=array();
		$footerCode=tblNavMenu_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>