<?php
// This script and data application were generated by AppGini 5.30
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/tblSidebarEntries.php");
	include("$currDir/tblSidebarEntries_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('tblSidebarEntries');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "tblSidebarEntries";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`tblSidebarEntries`.`ID`" => "ID",
		"`tblSidebarEntries`.`Title`" => "Title",
		"`tblSidebarEntries`.`Caption`" => "Caption",
		"IF(    CHAR_LENGTH(`tblAccessions1`.`ID`) || CHAR_LENGTH(`tblAccessions1`.`CaptionText`), CONCAT_WS('',   `tblAccessions1`.`ID`, ': ', `tblAccessions1`.`CaptionText`), '') /* AccessionID */" => "AccessionID",
		"`tblSidebarEntries`.`LinkURL`" => "LinkURL",
		"`tblSidebarEntries`.`ThumbnailID`" => "ThumbnailID",
		"if(`tblSidebarEntries`.`NewDateExpiration`,date_format(`tblSidebarEntries`.`NewDateExpiration`,'%m/%d/%Y'),'')" => "NewDateExpiration",
		"`tblSidebarEntries`.`Group`" => "Group",
		"`tblSidebarEntries`.`SortWithinGroup`" => "SortWithinGroup"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`tblSidebarEntries`.`ID`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`tblSidebarEntries`.`ThumbnailID`',
		7 => '`tblSidebarEntries`.`NewDateExpiration`',
		8 => '`tblSidebarEntries`.`Group`',
		9 => '`tblSidebarEntries`.`SortWithinGroup`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`tblSidebarEntries`.`ID`" => "ID",
		"`tblSidebarEntries`.`Title`" => "Title",
		"`tblSidebarEntries`.`Caption`" => "Caption",
		"IF(    CHAR_LENGTH(`tblAccessions1`.`ID`) || CHAR_LENGTH(`tblAccessions1`.`CaptionText`), CONCAT_WS('',   `tblAccessions1`.`ID`, ': ', `tblAccessions1`.`CaptionText`), '') /* AccessionID */" => "AccessionID",
		"`tblSidebarEntries`.`LinkURL`" => "LinkURL",
		"`tblSidebarEntries`.`ThumbnailID`" => "ThumbnailID",
		"if(`tblSidebarEntries`.`NewDateExpiration`,date_format(`tblSidebarEntries`.`NewDateExpiration`,'%m/%d/%Y'),'')" => "NewDateExpiration",
		"`tblSidebarEntries`.`Group`" => "Group",
		"`tblSidebarEntries`.`SortWithinGroup`" => "SortWithinGroup"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`tblSidebarEntries`.`ID`" => "ID",
		"`tblSidebarEntries`.`Title`" => "Title",
		"`tblSidebarEntries`.`Caption`" => "Caption",
		"IF(    CHAR_LENGTH(`tblAccessions1`.`ID`) || CHAR_LENGTH(`tblAccessions1`.`CaptionText`), CONCAT_WS('',   `tblAccessions1`.`ID`, ': ', `tblAccessions1`.`CaptionText`), '') /* AccessionID */" => "AccessionID",
		"`tblSidebarEntries`.`LinkURL`" => "LinkURL",
		"`tblSidebarEntries`.`ThumbnailID`" => "ThumbnailID",
		"`tblSidebarEntries`.`NewDateExpiration`" => "NewDateExpiration",
		"`tblSidebarEntries`.`Group`" => "Group",
		"`tblSidebarEntries`.`SortWithinGroup`" => "SortWithinGroup"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`tblSidebarEntries`.`ID`" => "ID",
		"`tblSidebarEntries`.`Title`" => "Title",
		"`tblSidebarEntries`.`Caption`" => "Caption",
		"IF(    CHAR_LENGTH(`tblAccessions1`.`ID`) || CHAR_LENGTH(`tblAccessions1`.`CaptionText`), CONCAT_WS('',   `tblAccessions1`.`ID`, ': ', `tblAccessions1`.`CaptionText`), '') /* AccessionID */" => "AccessionID",
		"`tblSidebarEntries`.`LinkURL`" => "LinkURL",
		"`tblSidebarEntries`.`ThumbnailID`" => "ThumbnailID",
		"if(`tblSidebarEntries`.`NewDateExpiration`,date_format(`tblSidebarEntries`.`NewDateExpiration`,'%m/%d/%Y'),'')" => "NewDateExpiration",
		"`tblSidebarEntries`.`Group`" => "Group",
		"`tblSidebarEntries`.`SortWithinGroup`" => "SortWithinGroup"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'AccessionID' => 'AccessionID');

	$x->QueryFrom="`tblSidebarEntries` LEFT JOIN `tblAccessions` as tblAccessions1 ON `tblAccessions1`.`ID`=`tblSidebarEntries`.`AccessionID` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "tblSidebarEntries_view.php";
	$x->RedirectAfterInsert = "tblSidebarEntries_view.php?SelectedID=#ID#";
	$x->TableTitle = "tblSidebarEntries";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`tblSidebarEntries`.`ID`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("ID", "Title", "Caption", "AccessionID", "LinkURL", "ThumbnailID", "NewDateExpiration", "Group", "SortWithinGroup");
	$x->ColFieldName = array('ID', 'Title', 'Caption', 'AccessionID', 'LinkURL', 'ThumbnailID', 'NewDateExpiration', 'Group', 'SortWithinGroup');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 7, 8, 9);

	$x->Template = 'templates/tblSidebarEntries_templateTV.html';
	$x->SelectedTemplate = 'templates/tblSidebarEntries_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblSidebarEntries`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblSidebarEntries' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblSidebarEntries`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblSidebarEntries' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`tblSidebarEntries`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tblSidebarEntries_init
	$render=TRUE;
	if(function_exists('tblSidebarEntries_init')){
		$args=array();
		$render=tblSidebarEntries_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tblSidebarEntries_header
	$headerCode='';
	if(function_exists('tblSidebarEntries_header')){
		$args=array();
		$headerCode=tblSidebarEntries_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: tblSidebarEntries_footer
	$footerCode='';
	if(function_exists('tblSidebarEntries_footer')){
		$args=array();
		$footerCode=tblSidebarEntries_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>