<?php
// This script and data application were generated by AppGini 5.30
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/tblUploadLogs.php");
	include("$currDir/tblUploadLogs_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('tblUploadLogs');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "tblUploadLogs";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`tblUploadLogs`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tblContributors1`.`ID`) || CHAR_LENGTH(`tblContributors1`.`LName`), CONCAT_WS('',   `tblContributors1`.`ID`, ': ', `tblContributors1`.`LName`), '') /* ContributorID */" => "ContributorID",
		"`tblUploadLogs`.`Log`" => "Log",
		"`tblUploadLogs`.`UploadDate`" => "UploadDate",
		"`tblUploadLogs`.`IP`" => "IP"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`tblUploadLogs`.`ID`',
		2 => 2,
		3 => 3,
		4 => '`tblUploadLogs`.`UploadDate`',
		5 => 5
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`tblUploadLogs`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tblContributors1`.`ID`) || CHAR_LENGTH(`tblContributors1`.`LName`), CONCAT_WS('',   `tblContributors1`.`ID`, ': ', `tblContributors1`.`LName`), '') /* ContributorID */" => "ContributorID",
		"`tblUploadLogs`.`Log`" => "Log",
		"`tblUploadLogs`.`UploadDate`" => "UploadDate",
		"`tblUploadLogs`.`IP`" => "IP"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`tblUploadLogs`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tblContributors1`.`ID`) || CHAR_LENGTH(`tblContributors1`.`LName`), CONCAT_WS('',   `tblContributors1`.`ID`, ': ', `tblContributors1`.`LName`), '') /* ContributorID */" => "ContributorID",
		"`tblUploadLogs`.`Log`" => "Log",
		"`tblUploadLogs`.`UploadDate`" => "UploadDate",
		"`tblUploadLogs`.`IP`" => "IP"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`tblUploadLogs`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`tblContributors1`.`ID`) || CHAR_LENGTH(`tblContributors1`.`LName`), CONCAT_WS('',   `tblContributors1`.`ID`, ': ', `tblContributors1`.`LName`), '') /* ContributorID */" => "ContributorID",
		"`tblUploadLogs`.`Log`" => "Log",
		"`tblUploadLogs`.`UploadDate`" => "UploadDate",
		"`tblUploadLogs`.`IP`" => "IP"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'ContributorID' => 'ContributorID');

	$x->QueryFrom="`tblUploadLogs` LEFT JOIN `tblContributors` as tblContributors1 ON `tblContributors1`.`ID`=`tblUploadLogs`.`ContributorID` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "tblUploadLogs_view.php";
	$x->RedirectAfterInsert = "tblUploadLogs_view.php?SelectedID=#ID#";
	$x->TableTitle = "tblUploadLogs";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`tblUploadLogs`.`ID`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("ID", "ContributorID", "Log", "UploadDate", "IP");
	$x->ColFieldName = array('ID', 'ContributorID', 'Log', 'UploadDate', 'IP');
	$x->ColNumber  = array(1, 2, 3, 4, 5);

	$x->Template = 'templates/tblUploadLogs_templateTV.html';
	$x->SelectedTemplate = 'templates/tblUploadLogs_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblUploadLogs`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblUploadLogs' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `tblUploadLogs`.`ID`=membership_userrecords.pkValue and membership_userrecords.tableName='tblUploadLogs' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`tblUploadLogs`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: tblUploadLogs_init
	$render=TRUE;
	if(function_exists('tblUploadLogs_init')){
		$args=array();
		$render=tblUploadLogs_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: tblUploadLogs_header
	$headerCode='';
	if(function_exists('tblUploadLogs_header')){
		$args=array();
		$headerCode=tblUploadLogs_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: tblUploadLogs_footer
	$footerCode='';
	if(function_exists('tblUploadLogs_footer')){
		$args=array();
		$footerCode=tblUploadLogs_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>